try:
   import sav_data.freeStuff
except:
   pass
try:
   import sav_data.mercerSphere
except:
   pass
try:
   import sav_data.readableNames
except:
   pass
try:
   import sav_data.resourcePurity
except:
   pass
try:
   import sav_data.slug
except:
   pass
try:
   import sav_data.somersloop
except:
   pass
try:
   import sav_data.crashSites
except:
   pass
try:
   import sav_data.hotbarShortcuts
except:
   pass
import enum

# New items can be identified for the ITEMS_FOR_PLAYER_INVENTORY tuple by
# enabling CHECK_ITEMS_FOR_PLAYER_INVENTORY in sav_cli.py and running:
#    py sav_cli.py --list-player-inventory <player-id> <file>
# This should also match sav_stack_sizes.json which can be checked using:
#    py sav_cli.py --add-missing-items-to-sav_stack_sizes
ITEMS_FOR_PLAYER_INVENTORY = (
   "/Game/FactoryGame/Equipment/Chainsaw/Desc_Chainsaw.Desc_Chainsaw_C",
   "/Game/FactoryGame/Equipment/NobeliskDetonator/Ammo/Desc_NobeliskCluster.Desc_NobeliskCluster_C",
   "/Game/FactoryGame/Equipment/NobeliskDetonator/Ammo/Desc_NobeliskGas.Desc_NobeliskGas_C",
   "/Game/FactoryGame/Equipment/NobeliskDetonator/Ammo/Desc_NobeliskShockwave.Desc_NobeliskShockwave_C",
   "/Game/FactoryGame/Equipment/RebarGun/Ammo/Desc_Rebar_Explosive.Desc_Rebar_Explosive_C",
   "/Game/FactoryGame/Equipment/RebarGun/Ammo/Desc_Rebar_Spreadshot.Desc_Rebar_Spreadshot_C",
   "/Game/FactoryGame/Equipment/RebarGun/Ammo/Desc_Rebar_Stunshot.Desc_Rebar_Stunshot_C",
   "/Game/FactoryGame/Equipment/Rifle/Ammo/Desc_CartridgeChaos.Desc_CartridgeChaos_C",
   "/Game/FactoryGame/Equipment/Rifle/Ammo/Desc_CartridgeSmartProjectile.Desc_CartridgeSmartProjectile_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_CandyCane.Desc_CandyCane_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_Gift.Desc_Gift_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_Snow.Desc_Snow_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_XmasBall1.Desc_XmasBall1_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_XmasBall2.Desc_XmasBall2_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_XmasBall3.Desc_XmasBall3_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_XmasBall4.Desc_XmasBall4_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_XmasBallCluster.Desc_XmasBallCluster_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_XmasBow.Desc_XmasBow_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_XmasBranch.Desc_XmasBranch_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_XmasStar.Desc_XmasStar_C",
   "/Game/FactoryGame/Events/Christmas/Parts/Desc_XmasWreath.Desc_XmasWreath_C",
   "/Game/FactoryGame/Prototype/WAT/Desc_WAT1.Desc_WAT1_C",
   "/Game/FactoryGame/Prototype/WAT/Desc_WAT2.Desc_WAT2_C",
   "/Game/FactoryGame/Resource/Environment/Berry/Desc_Berry.Desc_Berry_C",
   "/Game/FactoryGame/Resource/Environment/CrashSites/Desc_HardDrive.Desc_HardDrive_C",
   "/Game/FactoryGame/Resource/Environment/Crystal/Desc_Crystal.Desc_Crystal_C",
   "/Game/FactoryGame/Resource/Environment/Crystal/Desc_CrystalShard.Desc_CrystalShard_C",
   "/Game/FactoryGame/Resource/Environment/Crystal/Desc_Crystal_mk2.Desc_Crystal_mk2_C",
   "/Game/FactoryGame/Resource/Environment/Crystal/Desc_Crystal_mk3.Desc_Crystal_mk3_C",
   "/Game/FactoryGame/Resource/Environment/DesertShroom/Desc_Shroom.Desc_Shroom_C",
   "/Game/FactoryGame/Resource/Environment/Nut/Desc_Nut.Desc_Nut_C",
   "/Game/FactoryGame/Resource/Equipment/Beacon/Desc_Parachute.Desc_Parachute_C",
   "/Game/FactoryGame/Resource/Equipment/Cup/BP_EquipmentDescriptorCup.BP_EquipmentDescriptorCup_C",
   "/Game/FactoryGame/Resource/Equipment/Decoration/Desc_CharacterClap_Statue.Desc_CharacterClap_Statue_C",
   "/Game/FactoryGame/Resource/Equipment/Decoration/Desc_CharacterRunStatue.Desc_CharacterRunStatue_C",
   "/Game/FactoryGame/Resource/Equipment/Decoration/Desc_CharacterSpin_Statue.Desc_CharacterSpin_Statue_C",
   "/Game/FactoryGame/Resource/Equipment/Decoration/Desc_DoggoStatue.Desc_DoggoStatue_C",
   "/Game/FactoryGame/Resource/Equipment/Decoration/Desc_GoldenNut_Statue.Desc_GoldenNut_Statue_C",
   "/Game/FactoryGame/Resource/Equipment/Decoration/Desc_Hog_Statue.Desc_Hog_Statue_C",
   "/Game/FactoryGame/Resource/Equipment/Decoration/Desc_SpaceGiraffeStatue.Desc_SpaceGiraffeStatue_C",
   "/Game/FactoryGame/Resource/Equipment/GasMask/BP_EquipmentDescriptorGasmask.BP_EquipmentDescriptorGasmask_C",
   "/Game/FactoryGame/Resource/Equipment/GemstoneScanner/BP_EquipmentDescriptorObjectScanner.BP_EquipmentDescriptorObjectScanner_C",
   "/Game/FactoryGame/Resource/Equipment/GoldenCup/BP_EquipmentDescriptorCupGold.BP_EquipmentDescriptorCupGold_C",
   "/Game/FactoryGame/Resource/Equipment/GolfCart/Desc_GolfCart.Desc_GolfCart_C",
   "/Game/FactoryGame/Resource/Equipment/GolfCart/Desc_GolfCartGold.Desc_GolfCartGold_C",
   "/Game/FactoryGame/Resource/Equipment/HazmatSuit/BP_EquipmentDescriptorHazmatSuit.BP_EquipmentDescriptorHazmatSuit_C",
   "/Game/FactoryGame/Resource/Equipment/HoverPack/BP_EquipmentDescriptorHoverPack.BP_EquipmentDescriptorHoverPack_C",
   "/Game/FactoryGame/Resource/Equipment/JetPack/BP_EquipmentDescriptorJetPack.BP_EquipmentDescriptorJetPack_C",
   "/Game/FactoryGame/Resource/Equipment/JumpingStilts/BP_EquipmentDescriptorJumpingStilts.BP_EquipmentDescriptorJumpingStilts_C",
   "/Game/FactoryGame/Resource/Equipment/Medkit/Desc_Medkit.Desc_Medkit_C",
   "/Game/FactoryGame/Resource/Equipment/NailGun/Desc_RebarGunProjectile.Desc_RebarGunProjectile_C",
   "/Game/FactoryGame/Resource/Equipment/NobeliskDetonator/BP_EquipmentDescriptorNobeliskDetonator.BP_EquipmentDescriptorNobeliskDetonator_C",
   "/Game/FactoryGame/Resource/Equipment/PortableMiner/BP_ItemDescriptorPortableMiner.BP_ItemDescriptorPortableMiner_C",
   "/Game/FactoryGame/Resource/Equipment/Rifle/BP_EquipmentDescriptorRifle.BP_EquipmentDescriptorRifle_C",
   "/Game/FactoryGame/Resource/Equipment/ShockShank/BP_EquipmentDescriptorShockShank.BP_EquipmentDescriptorShockShank_C",
   "/Game/FactoryGame/Resource/Equipment/StunSpear/BP_EquipmentDescriptorStunSpear.BP_EquipmentDescriptorStunSpear_C",
   "/Game/FactoryGame/Resource/Equipment/Zipline/BP_EqDescZipLine.BP_EqDescZipLine_C",
   "/Game/FactoryGame/Resource/Parts/AlienDNACapsule/Desc_AlienDNACapsule.Desc_AlienDNACapsule_C",
   "/Game/FactoryGame/Resource/Parts/AlienPowerFuel/Desc_AlienPowerFuel.Desc_AlienPowerFuel_C",
   "/Game/FactoryGame/Resource/Parts/AlienProtein/Desc_AlienProtein.Desc_AlienProtein_C",
   "/Game/FactoryGame/Resource/Parts/AluminumCasing/Desc_AluminumCasing.Desc_AluminumCasing_C",
   "/Game/FactoryGame/Resource/Parts/AluminumIngot/Desc_AluminumIngot.Desc_AluminumIngot_C",
   "/Game/FactoryGame/Resource/Parts/AluminumPlate/Desc_AluminumPlate.Desc_AluminumPlate_C",
   "/Game/FactoryGame/Resource/Parts/AluminumPlateReinforced/Desc_AluminumPlateReinforced.Desc_AluminumPlateReinforced_C",
   "/Game/FactoryGame/Resource/Parts/AluminumScrap/Desc_AluminumScrap.Desc_AluminumScrap_C",
   "/Game/FactoryGame/Resource/Parts/AnimalParts/Desc_HatcherParts.Desc_HatcherParts_C",
   "/Game/FactoryGame/Resource/Parts/AnimalParts/Desc_HogParts.Desc_HogParts_C",
   "/Game/FactoryGame/Resource/Parts/AnimalParts/Desc_SpitterParts.Desc_SpitterParts_C",
   "/Game/FactoryGame/Resource/Parts/AnimalParts/Desc_StingerParts.Desc_StingerParts_C",
   "/Game/FactoryGame/Resource/Parts/Battery/Desc_Battery.Desc_Battery_C",
   "/Game/FactoryGame/Resource/Parts/BioFuel/Desc_Biofuel.Desc_Biofuel_C",
   "/Game/FactoryGame/Resource/Parts/BioFuel/Desc_PackagedBiofuel.Desc_PackagedBiofuel_C",
   "/Game/FactoryGame/Resource/Parts/Cable/Desc_Cable.Desc_Cable_C",
   "/Game/FactoryGame/Resource/Parts/CartridgeStandard/Desc_CartridgeStandard.Desc_CartridgeStandard_C",
   "/Game/FactoryGame/Resource/Parts/Cement/Desc_Cement.Desc_Cement_C",
   "/Game/FactoryGame/Resource/Parts/CircuitBoard/Desc_CircuitBoard.Desc_CircuitBoard_C",
   "/Game/FactoryGame/Resource/Parts/CircuitBoardHighSpeed/Desc_CircuitBoardHighSpeed.Desc_CircuitBoardHighSpeed_C",
   "/Game/FactoryGame/Resource/Parts/ColorCartridge/Desc_ColorCartridge.Desc_ColorCartridge_C",
   "/Game/FactoryGame/Resource/Parts/CompactedCoal/Desc_CompactedCoal.Desc_CompactedCoal_C",
   "/Game/FactoryGame/Resource/Parts/Computer/Desc_Computer.Desc_Computer_C",
   "/Game/FactoryGame/Resource/Parts/ComputerQuantum/Desc_ComputerQuantum.Desc_ComputerQuantum_C",
   "/Game/FactoryGame/Resource/Parts/ComputerSuper/Desc_ComputerSuper.Desc_ComputerSuper_C",
   "/Game/FactoryGame/Resource/Parts/CoolingSystem/Desc_CoolingSystem.Desc_CoolingSystem_C",
   "/Game/FactoryGame/Resource/Parts/CopperDust/Desc_CopperDust.Desc_CopperDust_C",
   "/Game/FactoryGame/Resource/Parts/CopperIngot/Desc_CopperIngot.Desc_CopperIngot_C",
   "/Game/FactoryGame/Resource/Parts/CopperSheet/Desc_CopperSheet.Desc_CopperSheet_C",
   "/Game/FactoryGame/Resource/Parts/CrystalOscillator/Desc_CrystalOscillator.Desc_CrystalOscillator_C",
   "/Game/FactoryGame/Resource/Parts/DarkMatter/Desc_DarkMatter.Desc_DarkMatter_C",
   "/Game/FactoryGame/Resource/Parts/Diamond/Desc_Diamond.Desc_Diamond_C",
   "/Game/FactoryGame/Resource/Parts/ElectromagneticControlRod/Desc_ElectromagneticControlRod.Desc_ElectromagneticControlRod_C",
   "/Game/FactoryGame/Resource/Parts/FicsiteIngot/Desc_FicsiteIngot.Desc_FicsiteIngot_C",
   "/Game/FactoryGame/Resource/Parts/FicsiteMesh/Desc_FicsiteMesh.Desc_FicsiteMesh_C",
   "/Game/FactoryGame/Resource/Parts/Ficsonium/Desc_Ficsonium.Desc_Ficsonium_C",
   "/Game/FactoryGame/Resource/Parts/FicsoniumFuelRod/Desc_FicsoniumFuelRod.Desc_FicsoniumFuelRod_C",
   "/Game/FactoryGame/Resource/Parts/Filter/Desc_Filter.Desc_Filter_C",
   "/Game/FactoryGame/Resource/Parts/FluidCanister/Desc_FluidCanister.Desc_FluidCanister_C",
   "/Game/FactoryGame/Resource/Parts/Fuel/Desc_Fuel.Desc_Fuel_C",
   "/Game/FactoryGame/Resource/Parts/GasTank/Desc_GasTank.Desc_GasTank_C",
   "/Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_Fabric.Desc_Fabric_C",
   "/Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_FlowerPetals.Desc_FlowerPetals_C",
   "/Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_GenericBiomass.Desc_GenericBiomass_C",
   "/Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_Leaves.Desc_Leaves_C",
   "/Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_Mycelia.Desc_Mycelia_C",
   "/Game/FactoryGame/Resource/Parts/GenericBiomass/Desc_Wood.Desc_Wood_C",
   "/Game/FactoryGame/Resource/Parts/GoldIngot/Desc_GoldIngot.Desc_GoldIngot_C",
   "/Game/FactoryGame/Resource/Parts/GunPowder/Desc_Gunpowder.Desc_Gunpowder_C",
   "/Game/FactoryGame/Resource/Parts/GunPowder/Desc_GunpowderMK2.Desc_GunpowderMK2_C",
   "/Game/FactoryGame/Resource/Parts/HUBParts/Desc_HUBParts.Desc_HUBParts_C",
   "/Game/FactoryGame/Resource/Parts/HighSpeedConnector/Desc_HighSpeedConnector.Desc_HighSpeedConnector_C",
   "/Game/FactoryGame/Resource/Parts/HighSpeedWire/Desc_HighSpeedWire.Desc_HighSpeedWire_C",
   "/Game/FactoryGame/Resource/Parts/IodineInfusedFilter/Desc_HazmatFilter.Desc_HazmatFilter_C",
   "/Game/FactoryGame/Resource/Parts/IonizedFuel/Desc_PackagedIonizedFuel.Desc_PackagedIonizedFuel_C",
   "/Game/FactoryGame/Resource/Parts/IronIngot/Desc_IronIngot.Desc_IronIngot_C",
   "/Game/FactoryGame/Resource/Parts/IronPlate/Desc_IronPlate.Desc_IronPlate_C",
   "/Game/FactoryGame/Resource/Parts/IronPlateReinforced/Desc_IronPlateReinforced.Desc_IronPlateReinforced_C",
   "/Game/FactoryGame/Resource/Parts/IronRod/Desc_IronRod.Desc_IronRod_C",
   "/Game/FactoryGame/Resource/Parts/IronScrew/Desc_IronScrew.Desc_IronScrew_C",
   "/Game/FactoryGame/Resource/Parts/ModularFrame/Desc_ModularFrame.Desc_ModularFrame_C",
   "/Game/FactoryGame/Resource/Parts/ModularFrameFused/Desc_ModularFrameFused.Desc_ModularFrameFused_C",
   "/Game/FactoryGame/Resource/Parts/ModularFrameHeavy/Desc_ModularFrameHeavy.Desc_ModularFrameHeavy_C",
   "/Game/FactoryGame/Resource/Parts/ModularFrameLightweight/Desc_ModularFrameLightweight.Desc_ModularFrameLightweight_C",
   "/Game/FactoryGame/Resource/Parts/Motor/Desc_Motor.Desc_Motor_C",
   "/Game/FactoryGame/Resource/Parts/MotorLightweight/Desc_MotorLightweight.Desc_MotorLightweight_C",
   "/Game/FactoryGame/Resource/Parts/NobeliskExplosive/Desc_NobeliskExplosive.Desc_NobeliskExplosive_C",
   "/Game/FactoryGame/Resource/Parts/PetroleumCoke/Desc_PetroleumCoke.Desc_PetroleumCoke_C",
   "/Game/FactoryGame/Resource/Parts/Plastic/Desc_Plastic.Desc_Plastic_C",
   "/Game/FactoryGame/Resource/Parts/PolymerResin/Desc_PolymerResin.Desc_PolymerResin_C",
   "/Game/FactoryGame/Resource/Parts/PressureConversionCube/Desc_PressureConversionCube.Desc_PressureConversionCube_C",
   "/Game/FactoryGame/Resource/Parts/QuantumOscillator/Desc_QuantumOscillator.Desc_QuantumOscillator_C",
   "/Game/FactoryGame/Resource/Parts/QuartzCrystal/Desc_QuartzCrystal.Desc_QuartzCrystal_C",
   "/Game/FactoryGame/Resource/Parts/ResourceSinkCoupon/Desc_ResourceSinkCoupon.Desc_ResourceSinkCoupon_C",
   "/Game/FactoryGame/Resource/Parts/RocketFuel/Desc_PackagedRocketFuel.Desc_PackagedRocketFuel_C",
   "/Game/FactoryGame/Resource/Parts/Rotor/Desc_Rotor.Desc_Rotor_C",
   "/Game/FactoryGame/Resource/Parts/Rubber/Desc_Rubber.Desc_Rubber_C",
   "/Game/FactoryGame/Resource/Parts/SAMFluctuator/Desc_SAMFluctuator.Desc_SAMFluctuator_C",
   "/Game/FactoryGame/Resource/Parts/SAMIngot/Desc_SAMIngot.Desc_SAMIngot_C",
   "/Game/FactoryGame/Resource/Parts/Silica/Desc_Silica.Desc_Silica_C",
   "/Game/FactoryGame/Resource/Parts/SingularityCell/Desc_SingularityCell.Desc_SingularityCell_C",
   "/Game/FactoryGame/Resource/Parts/SnowballProjectile/Desc_SnowballProjectile.Desc_SnowballProjectile_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_1.Desc_SpaceElevatorPart_1_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_10.Desc_SpaceElevatorPart_10_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_11.Desc_SpaceElevatorPart_11_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_12.Desc_SpaceElevatorPart_12_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_2.Desc_SpaceElevatorPart_2_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_3.Desc_SpaceElevatorPart_3_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_4.Desc_SpaceElevatorPart_4_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_5.Desc_SpaceElevatorPart_5_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_6.Desc_SpaceElevatorPart_6_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_7.Desc_SpaceElevatorPart_7_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_8.Desc_SpaceElevatorPart_8_C",
   "/Game/FactoryGame/Resource/Parts/SpaceElevatorParts/Desc_SpaceElevatorPart_9.Desc_SpaceElevatorPart_9_C",
   "/Game/FactoryGame/Resource/Parts/SpikedRebar/Desc_SpikedRebar.Desc_SpikedRebar_C",
   "/Game/FactoryGame/Resource/Parts/Stator/Desc_Stator.Desc_Stator_C",
   "/Game/FactoryGame/Resource/Parts/SteelIngot/Desc_SteelIngot.Desc_SteelIngot_C",
   "/Game/FactoryGame/Resource/Parts/SteelPipe/Desc_SteelPipe.Desc_SteelPipe_C",
   "/Game/FactoryGame/Resource/Parts/SteelPlate/Desc_SteelPlate.Desc_SteelPlate_C",
   "/Game/FactoryGame/Resource/Parts/SteelPlateReinforced/Desc_SteelPlateReinforced.Desc_SteelPlateReinforced_C",
   "/Game/FactoryGame/Resource/Parts/TemporalProcessor/Desc_TemporalProcessor.Desc_TemporalProcessor_C",
   "/Game/FactoryGame/Resource/Parts/TimeCrystal/Desc_TimeCrystal.Desc_TimeCrystal_C",
   "/Game/FactoryGame/Resource/Parts/Turbofuel/Desc_TurboFuel.Desc_TurboFuel_C",
   "/Game/FactoryGame/Resource/Parts/UraniumCell/Desc_UraniumCell.Desc_UraniumCell_C",
   "/Game/FactoryGame/Resource/Parts/Wire/Desc_Wire.Desc_Wire_C",
   "/Game/FactoryGame/Resource/RawResources/Coal/Desc_Coal.Desc_Coal_C",
   "/Game/FactoryGame/Resource/RawResources/OreBauxite/Desc_OreBauxite.Desc_OreBauxite_C",
   "/Game/FactoryGame/Resource/RawResources/OreCopper/Desc_OreCopper.Desc_OreCopper_C",
   "/Game/FactoryGame/Resource/RawResources/OreGold/Desc_OreGold.Desc_OreGold_C",
   "/Game/FactoryGame/Resource/RawResources/OreIron/Desc_OreIron.Desc_OreIron_C",
   "/Game/FactoryGame/Resource/RawResources/RawQuartz/Desc_RawQuartz.Desc_RawQuartz_C",
   "/Game/FactoryGame/Resource/RawResources/SAM/Desc_SAM.Desc_SAM_C",
   "/Game/FactoryGame/Resource/RawResources/Stone/Desc_Stone.Desc_Stone_C",
   "/Game/FactoryGame/Resource/RawResources/Sulfur/Desc_Sulfur.Desc_Sulfur_C",
   "/Game/FactoryGame/Resource/RawResources/Water/Desc_PackagedWater.Desc_PackagedWater_C",
)

CONVEYOR_BELTS = (
   "/Game/FactoryGame/Buildable/Factory/ConveyorBeltMk1/Build_ConveyorBeltMk1.Build_ConveyorBeltMk1_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorBeltMk2/Build_ConveyorBeltMk2.Build_ConveyorBeltMk2_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorBeltMk3/Build_ConveyorBeltMk3.Build_ConveyorBeltMk3_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorBeltMk4/Build_ConveyorBeltMk4.Build_ConveyorBeltMk4_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorBeltMk5/Build_ConveyorBeltMk5.Build_ConveyorBeltMk5_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorBeltMk6/Build_ConveyorBeltMk6.Build_ConveyorBeltMk6_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorLiftMk1/Build_ConveyorLiftMk1.Build_ConveyorLiftMk1_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorLiftMk2/Build_ConveyorLiftMk2.Build_ConveyorLiftMk2_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorLiftMk3/Build_ConveyorLiftMk3.Build_ConveyorLiftMk3_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorLiftMk4/Build_ConveyorLiftMk4.Build_ConveyorLiftMk4_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorLiftMk5/Build_ConveyorLiftMk5.Build_ConveyorLiftMk5_C",
   "/Game/FactoryGame/Buildable/Factory/ConveyorLiftMk6/Build_ConveyorLiftMk6.Build_ConveyorLiftMk6_C",
)

# When power slugs are collected, they change from 1 ActorHeader + 1 Object into 1 First-Collectable + 1 Second-Collectable
POWER_SLUG = (
   "/Game/FactoryGame/Resource/Environment/Crystal/BP_Crystal.BP_Crystal_C",
   "/Game/FactoryGame/Resource/Environment/Crystal/BP_Crystal_mk2.BP_Crystal_mk2_C",
   "/Game/FactoryGame/Resource/Environment/Crystal/BP_Crystal_mk3.BP_Crystal_mk3_C",
)

MINERS = (
   "/Game/FactoryGame/Buildable/Factory/MinerMK1/Build_MinerMk1.Build_MinerMk1_C", # From MinerMk1 to MinerMK1 in v1.0
   "/Game/FactoryGame/Buildable/Factory/MinerMk2/Build_MinerMk2.Build_MinerMk2_C",
   "/Game/FactoryGame/Buildable/Factory/MinerMk3/Build_MinerMk3.Build_MinerMk3_C",
   "/Game/FactoryGame/Buildable/Factory/OilPump/Build_OilPump.Build_OilPump_C",
   "/Game/FactoryGame/Buildable/Factory/FrackingSmasher/Build_FrackingSmasher.Build_FrackingSmasher_C",
   "/Game/FactoryGame/Buildable/Factory/FrackingExtractor/Build_FrackingExtractor.Build_FrackingExtractor_C",
   "/Game/FactoryGame/Buildable/Factory/GeneratorGeoThermal/Build_GeneratorGeoThermal.Build_GeneratorGeoThermal_C",
)

MINED_RESOURCES = (
   "/Game/FactoryGame/Resource/BP_ResourceNode.BP_ResourceNode_C",
   "/Game/FactoryGame/Resource/BP_FrackingCore.BP_FrackingCore_C",
   "/Game/FactoryGame/Resource/BP_FrackingSatellite.BP_FrackingSatellite_C",
   "/Game/FactoryGame/Resource/BP_ResourceNodeGeyser.BP_ResourceNodeGeyser_C",
   #"/Game/FactoryGame/Resource/BP_ResourceDeposit.BP_ResourceDeposit_C",  # These are manually harvested resource rocks which have the properties mResourceDepositTableIndex, mMineAmount, mResourcesLeft
)

POWER_LINE = (
   "/Game/FactoryGame/Buildable/Factory/PowerLine/Build_PowerLine.Build_PowerLine_C",
   "/Game/FactoryGame/Events/Christmas/Buildings/PowerLineLights/Build_XmassLightsLine.Build_XmassLightsLine_C")
CRASH_SITE = "/Game/FactoryGame/World/Benefit/DropPod/BP_DropPod.BP_DropPod_C"

SOMERSLOOP = "/Game/FactoryGame/Prototype/WAT/BP_WAT1.BP_WAT1_C"
MERCER_SPHERE = "/Game/FactoryGame/Prototype/WAT/BP_WAT2.BP_WAT2_C"
MERCER_SHRINE = "/Game/FactoryGame/Prototype/WAT/BP_MercerShrine.BP_MercerShrine_C"

# 89 hard drives (alternate recipes & inflated pocket dimention)
UNLOCK_PATHS__HARD_DRIVES = (
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_AdheredIronPlate.Schematic_Alternate_AdheredIronPlate_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_AlcladCasing.Schematic_Alternate_AlcladCasing_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_AutomatedMiner.Schematic_Alternate_AutomatedMiner_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_HighSpeedWiring.Schematic_Alternate_HighSpeedWiring_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Coal2.Schematic_Alternate_Coal2_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_BoltedFrame.Schematic_Alternate_BoltedFrame_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_ReinforcedIronPlate1.Schematic_Alternate_ReinforcedIronPlate1_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Screw.Schematic_Alternate_Screw_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_CircuitBoard2.Schematic_Alternate_CircuitBoard2_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Computer1.Schematic_Alternate_Computer1_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Wire2.Schematic_Alternate_Wire2_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Coal1.Schematic_Alternate_Coal1_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Silica.Schematic_Alternate_Silica_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_ClassicBattery.Schematic_Alternate_ClassicBattery_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_CoatedCable.Schematic_Alternate_CoatedCable_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_CoatedIronCanister.Schematic_Alternate_CoatedIronCanister_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_CoatedIronPlate.Schematic_Alternate_CoatedIronPlate_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_CokeSteelIngot.Schematic_Alternate_CokeSteelIngot_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_EnrichedCoal.Schematic_Alternate_EnrichedCoal_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_IngotSteel2.Schematic_Alternate_IngotSteel2_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_CoolingDevice.Schematic_Alternate_CoolingDevice_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_CopperAlloyIngot.Schematic_Alternate_CopperAlloyIngot_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_CopperRotor.Schematic_Alternate_CopperRotor_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Beacon1.Schematic_Alternate_Beacon1_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Computer2.Schematic_Alternate_Computer2_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_DilutedFuel.Schematic_Alternate_DilutedFuel_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_DilutedPackagedFuel.Schematic_Alternate_DilutedPackagedFuel_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_ElectricMotor.Schematic_Alternate_ElectricMotor_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_ElectroAluminumScrap.Schematic_Alternate_ElectroAluminumScrap_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_ElectrodeCircuitBoard.Schematic_Alternate_ElectrodeCircuitBoard_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_ElectromagneticControlRod1.Schematic_Alternate_ElectromagneticControlRod1_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_ReinforcedSteelPlate.Schematic_Alternate_ReinforcedSteelPlate_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_FertileUranium.Schematic_Alternate_FertileUranium_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Gunpowder1.Schematic_Alternate_Gunpowder1_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Concrete.Schematic_Alternate_Concrete_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_FlexibleFramework.Schematic_Alternate_FlexibleFramework_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Quickwire.Schematic_Alternate_Quickwire_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_FusedWire.Schematic_Alternate_FusedWire_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_HeatSink1.Schematic_Alternate_HeatSink1_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_HeatFusedFrame.Schematic_Alternate_HeatFusedFrame_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_HeavyModularFrame.Schematic_Alternate_HeavyModularFrame_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_HeavyFlexibleFrame.Schematic_Alternate_HeavyFlexibleFrame_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_HeavyOilResidue.Schematic_Alternate_HeavyOilResidue_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_UraniumCell1.Schematic_Alternate_UraniumCell1_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_InstantPlutoniumCell.Schematic_Alternate_InstantPlutoniumCell_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_InstantScrap.Schematic_Alternate_InstantScrap_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Cable1.Schematic_Alternate_Cable1_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_CrystalOscillator.Schematic_Alternate_CrystalOscillator_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_IngotIron.Schematic_Alternate_IngotIron_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Wire1.Schematic_Alternate_Wire1_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_OCSupercomputer.Schematic_Alternate_OCSupercomputer_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_PlasticSmartPlating.Schematic_Alternate_PlasticSmartPlating_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_PlutoniumFuelUnit.Schematic_Alternate_PlutoniumFuelUnit_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_PolymerResin.Schematic_Alternate_PolymerResin_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_PureAluminumIngot.Schematic_Alternate_PureAluminumIngot_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_PureCateriumIngot.Schematic_Alternate_PureCateriumIngot_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_PureCopperIngot.Schematic_Alternate_PureCopperIngot_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_PureIronIngot.Schematic_Alternate_PureIronIngot_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_PureQuartzCrystal.Schematic_Alternate_PureQuartzCrystal_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Cable2.Schematic_Alternate_Cable2_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Stator.Schematic_Alternate_Stator_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_RadioControlUnit1.Schematic_Alternate_RadioControlUnit1_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_RadioControlSystem.Schematic_Alternate_RadioControlSystem_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Plastic1.Schematic_Alternate_Plastic1_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_RecycledRubber.Schematic_Alternate_RecycledRubber_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Motor1.Schematic_Alternate_Motor1_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_RubberConcrete.Schematic_Alternate_RubberConcrete_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_CircuitBoard1.Schematic_Alternate_CircuitBoard1_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_HighSpeedConnector.Schematic_Alternate_HighSpeedConnector_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_SloppyAlumina.Schematic_Alternate_SloppyAlumina_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_IngotSteel1.Schematic_Alternate_IngotSteel1_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_SteamedCopperSheet.Schematic_Alternate_SteamedCopperSheet_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_SteelCanister.Schematic_Alternate_SteelCanister_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_SteelCoatedPlate.Schematic_Alternate_SteelCoatedPlate_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_SteelRod.Schematic_Alternate_SteelRod_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Rotor.Schematic_Alternate_Rotor_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_Screw2.Schematic_Alternate_Screw2_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_ModularFrame.Schematic_Alternate_ModularFrame_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_ReinforcedIronPlate2.Schematic_Alternate_ReinforcedIronPlate2_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_SuperStateComputer.Schematic_Alternate_SuperStateComputer_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_TurboBlendFuel.Schematic_Alternate_TurboBlendFuel_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_TurboMotor1.Schematic_Alternate_TurboMotor1_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_TurboHeavyFuel.Schematic_Alternate_TurboHeavyFuel_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update4/Schematic_Alternate_TurboPressureMotor.Schematic_Alternate_TurboPressureMotor_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_TurboFuel.Schematic_Alternate_TurboFuel_C",
   "/Game/FactoryGame/Schematics/Alternate/Parts/Schematic_Alternate_NuclearFuelRod1.Schematic_Alternate_NuclearFuelRod1_C",
   "/Game/FactoryGame/Schematics/Alternate/New_Update3/Schematic_Alternate_WetConcrete.Schematic_Alternate_WetConcrete_C",
   "/Game/FactoryGame/Schematics/Alternate/Upgrades/Schematic_Alternate_InventorySlots2.Schematic_Alternate_InventorySlots2_C",
   "/Game/FactoryGame/Schematics/Alternate/Upgrades/Schematic_Alternate_InventorySlots1.Schematic_Alternate_InventorySlots1_C",
)

# 80 awesome shop unlocks -- Also removed from "mAvailableSchematics" under Persistent_Level:PersistentLevel.BP_GameState_C_2147330588
UNLOCK_PATHS__AWESOME_SHOP = (
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_BeamSet.ResourceSink_BeamSet_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_Catwalks.ResourceSink_Catwalks_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_ConcretePillarSet.ResourceSink_ConcretePillarSet_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_FactoryBarrier.ResourceSink_FactoryBarrier_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_FactoryFence.ResourceSink_FactoryFence_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_FactoryRailing.ResourceSink_FactoryRailing_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_FoudationPillar.ResourceSink_FoudationPillar_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_FramePillarSet.ResourceSink_FramePillarSet_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_FrameworkFoundations.ResourceSink_FrameworkFoundations_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_Ladders.ResourceSink_Ladders_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_Roofs_Basic.ResourceSink_Roofs_Basic_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_Roofs_Corners.ResourceSink_Roofs_Corners_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_Stairs.ResourceSink_Stairs_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_Walkways.ResourceSink_Walkways_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Patterns/ResourceSink_Arrows_FoundationPatterns.ResourceSink_Arrows_FoundationPatterns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Customizer/ResourceSink_Customizer_Asphalt_FoundationMaterial.ResourceSink_Customizer_Asphalt_FoundationMaterial_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Customizer/ResourceSink_Customizer_Concrete_FoundationMaterial.ResourceSink_Customizer_Concrete_FoundationMaterial_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Customizer/ResourceSink_Customizer_ConcreteWallMaterial.ResourceSink_Customizer_ConcreteWallMaterial_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Customizer/ResourceSink_Customizer_GlassRoofMaterial.ResourceSink_Customizer_GlassRoofMaterial_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Customizer/ResourceSink_Customizer_GripMetal_FoundationMaterial.ResourceSink_Customizer_GripMetal_FoundationMaterial_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Customizer/ResourceSink_Customizer_PolishedConcrete_FoundationMaterial.ResourceSink_Customizer_PolishedConcrete_FoundationMaterial_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Customizer/ResourceSink_Customizer_SteelRoofMaterial.ResourceSink_Customizer_SteelRoofMaterial_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Customizer/ResourceSink_Customizer_SteelWallMaterial.ResourceSink_Customizer_SteelWallMaterial_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Customizer/ResourceSink_Customizer_TarRoofMaterial.ResourceSink_Customizer_TarRoofMaterial_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Patterns/ResourceSink_DotLines_FoundationPatterns.ResourceSink_DotLines_FoundationPatterns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Patterns/ResourceSink_FullLines_FoundationPatterns.ResourceSink_FullLines_FoundationPatterns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Patterns/ResourceSink_IconsFactory_FoundationPatterns.ResourceSink_IconsFactory_FoundationPatterns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Patterns/ResourceSink_IconsTransport_FoundationPatterns.ResourceSink_IconsTransport_FoundationPatterns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Patterns/ResourceSink_Number_FoundationPatterns.ResourceSink_Number_FoundationPatterns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Patterns/ResourceSink_Pathways_FoundationPatterns.ResourceSink_Pathways_FoundationPatterns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/Patterns/ResourceSink_Zones_FoundationPatterns.ResourceSink_Zones_FoundationPatterns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_CurvedFoundationPack.ResourceSink_CurvedFoundationPack_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_DiagonalRamps.ResourceSink_DiagonalRamps_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_FoundationExpansionPack.ResourceSink_FoundationExpansionPack_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_HalfFoundations.ResourceSink_HalfFoundations_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_InvertedCornerRamps.ResourceSink_InvertedCornerRamps_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_InvertedRampPack.ResourceSink_InvertedRampPack_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_QuarterPipeExtensions.ResourceSink_QuarterPipeExtensions_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_Checkmark.ResourceSink_Checkmark_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_CyberWagon.ResourceSink_CyberWagon_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_CyberWagon_Unlock.ResourceSink_CyberWagon_Unlock_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_FactoryCart.ResourceSink_FactoryCart_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_GoldenCart.ResourceSink_GoldenCart_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_GoldenCart_Unlock.ResourceSink_GoldenCart_Unlock_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_GoldenCup.ResourceSink_GoldenCup_C",
   "/Game/FactoryGame/Schematics/Tapes/Schematic_AbsoluteFicsit.Schematic_AbsoluteFicsit_C", # "/Game/FactoryGame/Resource/Tape/AbsoluteFicsit/Tape_AbsoluteFicsit.Tape_AbsoluteFicsit_C", "Absolute FICSIT", "ABSOLUTE FICSIT BOOMBOX TAPE"
   "/Game/FactoryGame/Schematics/Tapes/Schematic_Ficsday2025.Schematic_Ficsday2025_C",       # "/Game/FactoryGame/Resource/Tape/HappyFicsday/Tape_HappyFicsday.Tape_HappyFicsday_C", "Happy Ficsday", "FICSIT ANNIVERSARY"
   "/Game/FactoryGame/Schematics/Tapes/Schematic_Goat.Schematic_Goat_C",                     # "/Game/FactoryGame/Resource/Tape/Goat/Tape_WorstOfGoat.Tape_WorstOfGoat_C", "Worst of Goat Simulator", "GOAT MUSIC BOOMBOX TAPE"
   "/Game/FactoryGame/Schematics/Tapes/Schematic_JoelSyntholm.Schematic_JoelSyntholm_C",     # "/Game/FactoryGame/Resource/Tape/JoelSyntholm/Tape_JoelSyntholm.Tape_JoelSyntholm_C", "Joel Syntholm", "JOEL SYNTHOLM BOOMBOX TAPE"
   "/Game/FactoryGame/Schematics/Tapes/Schematic_LeMichael.Schematic_LeMichael_C",           # "/Game/FactoryGame/Resource/Tape/LeMichael/Tape_LeMichael.Tape_LeMichael_C", "Le Michael", "LE MICHAEL BOOMBOX TAPE"
   "/Game/FactoryGame/Schematics/Tapes/Schematic_Sanctum.Schematic_Sanctum_C",               # "/Game/FactoryGame/Resource/Tape/Sanctum/Tape_Sanctum.Tape_Sanctum_C", "Sanctum", "SANCTUM BOOMBOX TAPE"
   "/Game/FactoryGame/Schematics/Tapes/Schematic_Sanctum2.Schematic_Sanctum2_C",             # "/Game/FactoryGame/Resource/Tape/Sanctum2/Tape_Sanctum2.Tape_Sanctum2_C", "Sanctum 2", "SANCTUM 2 BOOMBOX TAPE"
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_ConveyorCeilingMount.ResourceSink_ConveyorCeilingMount_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_ConveyorLiftHole.ResourceSink_ConveyorLiftHole_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_ConveyorWallMount.ResourceSink_ConveyorWallMount_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_HyperTubeFloorHole.ResourceSink_HyperTubeFloorHole_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_HyperTubeWallAttachements.ResourceSink_HyperTubeWallAttachements_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_NoIndicator_PipelineMK1.ResourceSink_NoIndicator_PipelineMK1_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_NoIndicator_PipelineMK2.ResourceSink_NoIndicator_PipelineMK2_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_PipelineFloorHole.ResourceSink_PipelineFloorHole_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_PipelineWallAttachments.ResourceSink_PipelineWallAttachments_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_WallPowerPoles.ResourceSink_WallPowerPoles_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_WallPowerPolesMK2.ResourceSink_WallPowerPolesMK2_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_WallPowerPolesMK3.ResourceSink_WallPowerPolesMK3_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_BillboardSigns.ResourceSink_BillboardSigns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_CeilingLight.ResourceSink_CeilingLight_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_DisplaySigns.ResourceSink_DisplaySigns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_HazardBoxSkin.ResourceSink_HazardBoxSkin_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_LabelSigns.ResourceSink_LabelSigns_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_LightControlPanel.ResourceSink_LightControlPanel_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_LightTower.ResourceSink_LightTower_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_MedicalBoxSkin.ResourceSink_MedicalBoxSkin_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_StreetLight.ResourceSink_StreetLight_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_ConveryWalls_Normal.ResourceSink_ConveryWalls_Normal_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_Diagonal_Down_Wallset.ResourceSink_Diagonal_Down_Wallset_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_Diagonal_Up_WallSet.ResourceSink_Diagonal_Up_WallSet_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_DoorWalls_Normal.ResourceSink_DoorWalls_Normal_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_FrameWindows.ResourceSink_FrameWindows_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_GateWalls.ResourceSink_GateWalls_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_Tilted_Walls.ResourceSink_Tilted_Walls_C",
   "/Game/FactoryGame/Schematics/ResourceSink/ResourceSink_WindowedWalls.ResourceSink_WindowedWalls_C",
)

# 85 MAM unlocks -- This also includes "mUnlockedResearchTrees" under Persistent_Level:PersistentLevel.BP_GameState_C_2147330588
UNLOCK_PATHS__MAM = (
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_ACarapace_2.Research_ACarapace_2_C",
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_ACarapace_3.Research_ACarapace_3_C",
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_AO_DNACapsule.Research_AO_DNACapsule_C",
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_AO_Hatcher.Research_AO_Hatcher_C",
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_AO_Hog.Research_AO_Hog_C",
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_AO_Pre_Rebar.Research_AO_Pre_Rebar_C",
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_AO_Spitter.Research_AO_Spitter_C",
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_AO_Stinger.Research_AO_Stinger_C",
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_AOrganisms_2.Research_AOrganisms_2_C",
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_AOrgans_2.Research_AOrgans_2_C",
   "/Game/FactoryGame/Schematics/Research/AlienOrganisms_RS/Research_AOrgans_3.Research_AOrgans_3_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_0.Research_Caterium_0_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_1.Research_Caterium_1_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_2_1.Research_Caterium_2_1_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_2.Research_Caterium_2_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_3_2.Research_Caterium_3_2_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_3.Research_Caterium_3_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_4_1_1.Research_Caterium_4_1_1_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_4_1_2.Research_Caterium_4_1_2_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_4_1.Research_Caterium_4_1_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_4_2.Research_Caterium_4_2_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_5_1.Research_Caterium_5_1_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_5.Research_Caterium_5_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_6_1.Research_Caterium_6_1_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_6_2.Research_Caterium_6_2_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_6_3.Research_Caterium_6_3_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_7_1.Research_Caterium_7_1_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_7_2.Research_Caterium_7_2_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_1.Research_XMas_1_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_1-1.Research_XMas_1-1_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_1-2.Research_XMas_1-2_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_2.Research_XMas_2_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_2-1.Research_XMas_2-1_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_2-2.Research_XMas_2-2_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_3.Research_XMas_3_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_3-1.Research_XMas_3-1_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_3-2.Research_XMas_3-2_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_4.Research_XMas_4_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_4-1.Research_XMas_4-1_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_4-2.Research_XMas_4-2_C",
   "/Game/FactoryGame/Schematics/Research/XMas_RS/Research_XMas_5.Research_XMas_5_C",
   "/Game/FactoryGame/Schematics/Research/Mycelia_RS/Research_Mycelia_1.Research_Mycelia_1_C",
   "/Game/FactoryGame/Schematics/Research/Mycelia_RS/Research_Mycelia_2_1.Research_Mycelia_2_1_C",
   "/Game/FactoryGame/Schematics/Research/Mycelia_RS/Research_Mycelia_2.Research_Mycelia_2_C",
   "/Game/FactoryGame/Schematics/Research/Mycelia_RS/Research_Mycelia_3.Research_Mycelia_3_C",
   "/Game/FactoryGame/Schematics/Research/Mycelia_RS/Research_Mycelia_4.Research_Mycelia_4_C",
   "/Game/FactoryGame/Schematics/Research/Mycelia_RS/Research_Mycelia_5.Research_Mycelia_5_C",
   "/Game/FactoryGame/Schematics/Research/Mycelia_RS/Research_Mycelia_6.Research_Mycelia_6_C",
   "/Game/FactoryGame/Schematics/Research/Mycelia_RS/Research_Mycelia_7.Research_Mycelia_7_C",
   "/Game/FactoryGame/Schematics/Research/Mycelia_RS/Research_Mycelia_8.Research_Mycelia_8_C",
   "/Game/FactoryGame/Schematics/Research/Nutrients_RS/Research_Nutrients_0.Research_Nutrients_0_C",
   "/Game/FactoryGame/Schematics/Research/Nutrients_RS/Research_Nutrients_1.Research_Nutrients_1_C",
   "/Game/FactoryGame/Schematics/Research/Nutrients_RS/Research_Nutrients_2.Research_Nutrients_2_C",
   "/Game/FactoryGame/Schematics/Research/Nutrients_RS/Research_Nutrients_3.Research_Nutrients_3_C",
   "/Game/FactoryGame/Schematics/Research/Nutrients_RS/Research_Nutrients_4.Research_Nutrients_4_C",
   "/Game/FactoryGame/Schematics/Research/PowerSlugs_RS/Research_PowerSlugs_1.Research_PowerSlugs_1_C",
   "/Game/FactoryGame/Schematics/Research/PowerSlugs_RS/Research_PowerSlugs_2.Research_PowerSlugs_2_C",
   "/Game/FactoryGame/Schematics/Research/PowerSlugs_RS/Research_PowerSlugs_3.Research_PowerSlugs_3_C",
   "/Game/FactoryGame/Schematics/Research/PowerSlugs_RS/Research_PowerSlugs_4.Research_PowerSlugs_4_C",
   "/Game/FactoryGame/Schematics/Research/PowerSlugs_RS/Research_PowerSlugs_5.Research_PowerSlugs_5_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_3_1.Research_Caterium_3_1_C",
   "/Game/FactoryGame/Schematics/Research/Caterium_RS/Research_Caterium_4_3.Research_Caterium_4_3_C",
   "/Game/FactoryGame/Schematics/Research/Quartz_RS/Research_Quartz_0.Research_Quartz_0_C",
   "/Game/FactoryGame/Schematics/Research/Quartz_RS/Research_Quartz_1_1.Research_Quartz_1_1_C",
   "/Game/FactoryGame/Schematics/Research/Quartz_RS/Research_Quartz_1_2.Research_Quartz_1_2_C",
   "/Game/FactoryGame/Schematics/Research/Quartz_RS/Research_Quartz_2_1.Research_Quartz_2_1_C",
   "/Game/FactoryGame/Schematics/Research/Quartz_RS/Research_Quartz_2.Research_Quartz_2_C",
   "/Game/FactoryGame/Schematics/Research/Quartz_RS/Research_Quartz_3_1.Research_Quartz_3_1_C",
   "/Game/FactoryGame/Schematics/Research/Quartz_RS/Research_Quartz_3_4.Research_Quartz_3_4_C",
   "/Game/FactoryGame/Schematics/Research/Quartz_RS/Research_Quartz_4_1.Research_Quartz_4_1_C",
   "/Game/FactoryGame/Schematics/Research/Quartz_RS/Research_Quartz_4.Research_Quartz_4_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_0.Research_Sulfur_0_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_1.Research_Sulfur_1_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_3_1.Research_Sulfur_3_1_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_3.Research_Sulfur_3_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_4_1.Research_Sulfur_4_1_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_4_2.Research_Sulfur_4_2_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_4.Research_Sulfur_4_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_5_1.Research_Sulfur_5_1_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_5_2.Research_Sulfur_5_2_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_5.Research_Sulfur_5_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_6.Research_Sulfur_6_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_compactedCoal.Research_Sulfur_CompactedCoal_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_ExperimentalPower.Research_Sulfur_ExperimentalPower_C",
   "/Game/FactoryGame/Schematics/Research/Sulfur_RS/Research_Sulfur_TurboFuel.Research_Sulfur_TurboFuel_C",
)

# 47 Tiers -- This also get removed from "mAvailableSchematics" under Persistent_Level:PersistentLevel.BP_GameState_C_2147330588
UNLOCK_PATHS__HUB_TIERS = (
   "/Game/FactoryGame/Schematics/Schematic_StartingRecipes.Schematic_StartingRecipes_C",
   "/Game/FactoryGame/Schematics/Tutorial/Schematic_Tutorial1_5.Schematic_Tutorial1_5_C",
   "/Game/FactoryGame/Schematics/Tutorial/Schematic_Tutorial1.Schematic_Tutorial1_C",
   "/Game/FactoryGame/Schematics/Tutorial/Schematic_Tutorial2.Schematic_Tutorial2_C",
   "/Game/FactoryGame/Schematics/Tutorial/Schematic_Tutorial3.Schematic_Tutorial3_C",
   "/Game/FactoryGame/Schematics/Tutorial/Schematic_Tutorial4.Schematic_Tutorial4_C",
   "/Game/FactoryGame/Schematics/Tutorial/Schematic_Tutorial5.Schematic_Tutorial5_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_1-1.Schematic_1-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_1-2.Schematic_1-2_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_1-3.Schematic_1-3_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_2-1.Schematic_2-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_2-2.Schematic_2-2_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_2-3.Schematic_2-3_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_2-5.Schematic_2-5_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_3-2.Schematic_3-2_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_3-1.Schematic_3-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_3-3.Schematic_3-3_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_3-4.Schematic_3-4_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_4-2.Schematic_4-2_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_4-1.Schematic_4-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_4-3.Schematic_4-3_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_4-4.Schematic_4-4_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_4-5.Schematic_4-5_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_5-3.Schematic_5-3_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_5-1.Schematic_5-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_5-1-1.Schematic_5-1-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_5-2.Schematic_5-2_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_5-4.Schematic_5-4_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_5-4-1.Schematic_5-4-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_6-4.Schematic_6-4_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_6-1.Schematic_6-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_6-2.Schematic_6-2_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_6-3.Schematic_6-3_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_6-5.Schematic_6-5_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_7-1.Schematic_7-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_7-1-1.Schematic_7-1-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_7-2.Schematic_7-2_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_7-3.Schematic_7-3_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_7-4.Schematic_7-4_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_7-4-1.Schematic_7-4-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_7-5.Schematic_7-5_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_8-3.Schematic_8-3_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_8-1.Schematic_8-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_8-2.Schematic_8-2_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_8-2-1.Schematic_8-2-1_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_8-4.Schematic_8-4_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_8-5.Schematic_8-5_C",
   "/Game/FactoryGame/Schematics/Progression/Schematic_8-5-1.Schematic_8-5-1_C",
)

# 11 "special"
UNLOCK_PATHS__SPECIAL = (
   "/Game/FactoryGame/Events/Christmas/Calendar_Schematics/Ficsmas_Schematic_FingerGun_Emote.Ficsmas_Schematic_FingerGun_Emote_C",
   "/Game/FactoryGame/Events/Christmas/Calendar_Schematics/Ficsmas_Schematic_Fireworks.Ficsmas_Schematic_Fireworks_C",
   "/Game/FactoryGame/Events/Christmas/Calendar_Schematics/Ficsmas_Schematic_SkinBundle_1.Ficsmas_Schematic_SkinBundle_1_C",
   "/Game/FactoryGame/Events/Christmas/Calendar_Schematics/Ficsmas_Schematic_SkinBundle_2.Ficsmas_Schematic_SkinBundle_2_C",
   "/Game/FactoryGame/Schematics/Tapes/Schematic_DeepRockGalactic.Schematic_DeepRockGalactic_C",
   "/Game/FactoryGame/Schematics/Tapes/Schematic_Huntdown.Schematic_Huntdown_C",
   "/Game/FactoryGame/Schematics/Tapes/Schematic_SongsOfConquest.Schematic_SongsOfConquest_C",
   "/Game/FactoryGame/Events/Christmas/Buildings/TreeDecor/Schematic_XMassTree_T1.Schematic_XMassTree_T1_C",
   "/Game/FactoryGame/Events/Christmas/Buildings/TreeDecor/Schematic_XMassTree_T2.Schematic_XMassTree_T2_C",
   "/Game/FactoryGame/Events/Christmas/Buildings/TreeDecor/Schematic_XMassTree_T3.Schematic_XMassTree_T3_C",
   "/Game/FactoryGame/Events/Christmas/Buildings/TreeDecor/Schematic_XMassTree_T4.Schematic_XMassTree_T4_C",
)

UNLOCK_PATHS__COLLECTABLES = (
   # First path for unlockSubsystem. Second path for schematicManager.
   # First name is in boombox. Second name is in world.
   ("/Game/FactoryGame/Resource/Tape/SongsOfConquest/Tape_SongsOfConquest.Tape_SongsOfConquest_C",
    "/Game/FactoryGame/Schematics/Tapes/Schematic_SongsOfConquest.Schematic_SongsOfConquest_C",
    ("Songs of Conquest", "Conquest Boombox Tape"), (-37200, -60900)),

   ("/Game/FactoryGame/Resource/Tape/DeepRockGalactic/Tape_DeepRockGalactic.Tape_DeepRockGalactic_C",
    "/Game/FactoryGame/Schematics/Tapes/Schematic_DeepRockGalactic.Schematic_DeepRockGalactic_C",
    ("Deep Rock Galactic", "Deep Rock Galactic Boombox Tape"), (-125200, 168500)), # Cave -99200,159000

   ("/Game/FactoryGame/Resource/Tape/Huntdown/Tape_Huntdown.Tape_Huntdown_C",
    "/Game/FactoryGame/Schematics/Tapes/Schematic_Huntdown.Schematic_Huntdown_C",
    ("Huntdown", "Huntdown Boombox Tape"), (195000, -187700)),

   ("/Game/FactoryGame/Buildable/Factory/Locker/Helmets/Desc_Helmet_Beta.Desc_Helmet_Beta_C",
    "/Game/FactoryGame/Schematics/Pioneercosmetics/Helmets/Schematic_Helmet_Beta.Schematic_Helmet_Beta_C",
    "B-374 Helmet", (-160400, 66400)),
)

PROJECT_ASSEMBLY_COSTS = {
   "/Game/FactoryGame/GamePhases/GP_Project_Assembly_Phase_1.GP_Project_Assembly_Phase_1": {
      "Smart Plating": 50,
   },
   "/Game/FactoryGame/GamePhases/GP_Project_Assembly_Phase_2.GP_Project_Assembly_Phase_2": {
      "Smart Plating": 1000,
      "Versatile Framework": 1000,
      "Automated Wiring": 100,
   },
   "/Game/FactoryGame/GamePhases/GP_Project_Assembly_Phase_3.GP_Project_Assembly_Phase_3": {
      "Versatile Framework": 2500,
      "Modular Engine": 500,
      "Adaptive Control Unit": 100,
   },
   "/Game/FactoryGame/GamePhases/GP_Project_Assembly_Phase_4.GP_Project_Assembly_Phase_4": {
      "Assembly Director System": 500,
      "Magnetic Field Generator": 500,
      "Nuclear Pasta": 100,
      "Thermal Propulsion Rocket": 250,
   },
   "/Game/FactoryGame/GamePhases/GP_Project_Assembly_Phase_5.GP_Project_Assembly_Phase_5": {
      "Nuclear Pasta": 1000,
      "Biochemical Sculptor": 1000,
      "AI Expansion Server": 256,
      "Ballistic Warp Drive": 200,
   },
}
FINAL_PROJECT_ASSEMBLY_PHASE_6 = "/Game/FactoryGame/GamePhases/GP_Project_Assembly_Phase_6.GP_Project_Assembly_Phase_6"
FINAL_PROJECT_ASSEMBLY_PHASE_7 = "/Game/FactoryGame/GamePhases/GP_Project_Assembly_Phase_7.GP_Project_Assembly_Phase_7"

# https://satisfactory.wiki.gg/wiki/Milestones
MILESTONE_COSTS = {
   # Tier 0: Onboarding
   "HUB Upgrade 1": {
      "Iron Rod": 10,
   },
   "HUB Upgrade 2": {
      "Iron Rod": 20,
      "Iron Plate": 10,
   },
   "HUB Upgrade 3": {
      "Iron Plate": 20,
      "Iron Rod": 20,
      "Wire": 20,
   },
   "HUB Upgrade 4": {
      "Iron Plate": 75,
      "Cable": 20,
      "Concrete": 10,
   },
   "HUB Upgrade 5": {
      "Iron Rod": 75,
      "Cable": 50,
      "Concrete": 20,
   },
   "HUB Upgrade 6": {
      "Iron Rod": 100,
      "Iron Plate": 100,
      "Wire": 100,
      "Concrete": 50,
   },
   # Tier 1
   "Base Building": {
      "Concrete": 200,
      "Iron Plate": 100,
      "Iron Rod": 100,
   },
   "Logistics": {
      "Iron Plate": 150,
      "Iron Rod": 150,
      "Wire": 300,
   },
   "Field Research": {
      "Wire": 300,
      "Screw": 300,
      "Iron Plate": 100,
   },
   # Tier 2
   "Part Assembly": {
      "Cable": 200,
      "Iron Rod": 200,
      "Screw": 500,
      "Iron Plate": 300,
   },
   "Obstacle Clearing": {
      "Screw": 500,
      "Cable": 100,
      "Concrete": 100,
   },
   "Jump Pads": {
      "Rotor": 50,
      "Iron Plate": 300,
      "Cable": 150,
   },
   "Resource Sink Bonus Program": {
      "Concrete": 400,
      "Wire": 500,
      "Iron Rod": 200,
      "Iron Plate": 200,
   },
   "Logistics Mk.2": {
      "Reinforced Iron Plate": 50,
      "Concrete": 200,
      "Iron Rod": 300,
      "Iron Plate": 300,
   },
   # Tier 3
   "Coal Power": {
      "Reinforced Iron Plate": 150,
      "Rotor": 50,
      "Cable": 500,
   },
   "Vehicular Transport": {
      "Modular Frame": 25,
      "Rotor": 100,
      "Cable": 200,
      "Iron Rod": 400,
   },
   "Basic Steel Production": {
      "Modular Frame": 50,
      "Rotor": 150,
      "Concrete": 500,
      "Wire": 1000,
   },
   "Enhanced Asset Security": {
      "Reinforced Iron Plate": 100,
      "Iron Rod": 600,
      "Wire": 1500,
   },
   # Tier 4
   "FICSIT Blueprints": {
      "Modular Frame": 100,
      "Steel Beam": 200,
      "Cable": 500,
      "Concrete": 1000,
   },
   "Logistics Mk.3": {
      "Steel Beam": 200,
      "Steel Pipe": 200,
      "Reinforced Iron Plate": 400,
   },
   "Advanced Steel Production": {
      "Steel Pipe": 100,
      "Modular Frame": 100,
      "Rotor": 200,
      "Concrete": 500,
   },
   "Expanded Power Infrastructure": {
      "Encased Industrial Beam": 50,
      "Steel Beam": 100,
      "Modular Frame": 200,
      "Wire": 2000,
   },
   "Hypertubes": {
      "Encased Industrial Beam": 50,
      "Steel Pipe": 300,
      "Copper Sheet": 500,
   },
   # Tier 5
   "Jetpack": {
      "Motor": 50,
      "Cable": 1000,
      "Iron Plate": 1000,
   },
   "Oil Processing": {
      "Motor": 50,
      "Encased Industrial Beam": 100,
      "Steel Pipe": 500,
      "Copper Sheet": 500,
   },
   "Logistics Mk.4": {
      "Rubber": 200,
      "Encased Industrial Beam": 300,
      "Modular Frame": 400,
   },
   "Fluid Packaging": {
      "Plastic": 200,
      "Steel Beam": 400,
      "Copper Sheet": 1000,
   },
   "Petroleum Power": {
      "Motor": 100,
      "Encased Industrial Beam": 100,
      "Rubber": 200,
      "Plastic": 200,
   },
   # Tier 6
   "Industrial Manufacturing": {
      "Motor": 200,
      "Modular Frame": 200,
      "Plastic": 400,
      "Cable": 1000,
   },
   "Monorail Train Technology": {
      "Motor": 250,
      "Encased Industrial Beam": 500,
      "Steel Beam": 100,
      "Steel Pipe": 1000,
   },
   "Railway Signaling": {
      "Computer": 50,
      "Steel Pipe": 400,
      "Copper Sheet": 1000,
   },
   "Pipeline Engineering Mk.2": {
      "Heavy Modular Frame": 50,
      "Plastic": 500,
      "Rubber": 500,
   },
   "FICSIT Blueprints Mk.2": {
      "Heavy Modular Frame": 100,
      "Computer": 200,
      "Rubber": 400,
      "Concrete": 1500,
   },
   # Tier 7
   "Bauxite Refinement": {
      "Computer": 100,
      "Heavy Modular Frame": 100,
      "Motor": 200,
      "Rubber": 500,
   },
   "Hover Pack": {
      "Alclad Aluminum Sheet": 100,
      "Heavy Modular Frame": 100,
      "Computer": 100,
      "Motor": 250,
   },
   "Logistics Mk.5": {
      "Alclad Aluminum Sheet": 200,
      "Encased Industrial Beam": 400,
      "Reinforced Iron Plate": 600,
   },
   "Hazmat Suit": {
      "Gas Filter": 50,
      "Aluminum Casing": 100,
      "Quickwire": 500,
   },
   "Control System Development": {
      "Alclad Aluminum Sheet": 200,
      "Aluminum Casing": 400,
      "Computer": 200,
      "Plastic": 1000,
   },
   # Tier 8
   "Aeronautical Engineering": {
      "Radio Control Unit": 50,
      "Alclad Aluminum Sheet": 100,
      "Aluminum Casing": 200,
      "Motor": 300,
   },
   "Nuclear Power": {
      "Supercomputer": 50,
      "Heavy Modular Frame": 200,
      "Cable": 1000,
      "Concrete": 2000,
   },
   "Advanced Aluminum Production": {
      "Radio Control Unit": 50,
      "Aluminum Casing": 200,
      "Alclad Aluminum Sheet": 400,
      "Wire": 3000,
   },
   "Leading-edge Production": {
      "Fused Modular Frame": 50,
      "Supercomputer": 100,
      "Steel Pipe": 1000,
   },
   "Particle Enrichment": {
      "Turbo Motor": 50,
      "Fused Modular Frame": 100,
      "Cooling System": 200,
      "Quickwire": 2500,
   },
   # Tier 9
   "Matter Conversion": {
      "Fused Modular Frame": 100,
      "Radio Control Unit": 250,
      "Cooling System": 500,
   },
   "Quantum Encoding": {
      "Time Crystal": 50,
      "Ficsite Trigon": 100,
      "Turbo Motor": 200,
      "Supercomputer": 400,
   },
   "FICSIT Blueprints Mk.3": {
      "Neural-Quantum Processor": 100,
      "Time Crystal": 250,
      "Ficsite Trigon": 500,
      "Fused Modular Frame": 500,
   },
   "Spatial Energy Regulation": {
      "Superposition Oscillator": 100,
      "Turbo Motor": 250,
      "Radio Control Unit": 500,
      "SAM Fluctuator": 1000,
   },
   "Peak Efficiency": {
      "Time Crystal": 250,
      "Ficsite Trigon": 250,
      "Alclad Aluminum Sheet": 5000,
      "Iron Plate": 10000,
   },
}

class ECompassViewDistance(enum.Enum):
   CVD_Off = 1
   CVD_Near = 2
   CVD_Mid = 3 # "Medium"
   CVD_Far = 4
   CVD_Always = 5 # "Infinite"

COMPASS_VIEW_DISTANCES__ENUM_TO_NAME = {
   ECompassViewDistance.CVD_Off: "Off",
   ECompassViewDistance.CVD_Near: "Near",
   ECompassViewDistance.CVD_Mid: "Medium",
   ECompassViewDistance.CVD_Far: "Far",
   ECompassViewDistance.CVD_Always: "Infinite"
}

COMPASS_VIEW_DISTANCES__NAME_TO_ENUM = {
   "Off": ECompassViewDistance.CVD_Off,
   "Near": ECompassViewDistance.CVD_Near,
   "Medium": ECompassViewDistance.CVD_Mid,
   "Far": ECompassViewDistance.CVD_Far,
   "Infinite": ECompassViewDistance.CVD_Always
}

ICON_IDS_TO_NAMES = {
   # Stamps
   650: "Biomass [Stamp]",
   651: "Cave",
   652: "Crash",
   653: "Crate",
   654: "Creature",
   656: "Question Mark [Stamp]",
   657: "Fluids",
   659: "Radiation [Stamp]",
   660: "Rock",
   661: "Warning [Stamp]",
   662: "Fruit",
   663: "Slug",

   # Monochrome
   329: "Arrow Down",
   330: "Arrow Down Left",
   331: "Arrow Down Right",
   332: "Arrow Left",
   333: "Arrow Up Left",
   334: "Arrow Up",
   335: "Arrow Up Right",
   336: "Arrow Right",
   337: "Drop",
   338: "Radiation [Monochrome]",
   339: "Thumb Up",
   340: "Thumb Down",
   341: "Stop X",
   342: "Road Arrow Down",
   343: "Road Arrow Turn Around",
   344: "Road Arrow Turn Left",
   345: "Road Arrow Turn Right",
   346: "Road Arrow Up",
   347: "Storage Crate",
   348: "Exit Door",
   349: "Factory",
   350: "Home House",
   351: "Player Pioneer",
   352: "Power",
   353: "Vehicle Tractor",
   354: "Vehicle Explorer",
   355: "Vehicle Truck",
   356: "Vehicle Train",
   357: "Vehicle Factory Cart",
   358: "Vehicle Drone",
   362: "Warning [Monochrome]",
   598: "FICSIT Check Mark",
   644: "Recycle",
   645: "Trash",
   782: "Question Mark [Monochrome]",

   # Buildings
   1: "The HUB",
   2: "Craft Bench",
   3: "Equipment Workshop",
   4: "Smelter",
   5: "Power Line",
   6: "Constructor",
   7: "Power Pole Mk.1",
   8: "Conveyor Pole",
   9: "Conveyor Belt Mk.1",
   10: "Miner Mk.1",
   11: "Storage Container",
   12: "Space Elevator",
   13: "Biomass Burner (without input)",
   14: "Giant FICSMAS Tree",
   16: "N/A (Foundation 8x4)",
   18: "Ceiling Light",
   19: "Wall-Mounted Flood Light",
   20: "Flood Light Tower",
   21: "Lights Control Panel",
   22: "Resource Well Pressurizer",
   23: "Resource Well Extractor",
   25: "Ladder",
   26: "Drone Port",
   29: "Panel Window",
   31: "Old Tilted Jump Pad",
   32: "Power Pole Mk.2",
   33: "Wall Outlet Mk.2",
   34: "Double Wall Outlet Mk.2",
   35: "Smart Splitter",
   38: "Lookout Tower",
   39: "Foundations (8m x 1m)",
   40: "Foundations (8m x 2m)",
   41: "Ramps (8m x 1m)",
   42: "Ramps (8m x 2m)",
   43: "Ramps (8m x 4m)",
   45: "Conveyor Splitter",
   46: "Conveyor Merger",
   47: "Conveyor Lift Mk.1",
   48: "MAM",
   49: "Personal Storage Box",
   51: "Conveyor Wall x3 (Orange)",
   52: "Conveyor Wall x2 (Orange)",
   53: "Conveyor Wall x1 (Orange)",
   54: "Conveyor Wall x3 (Metal)",
   55: "Conveyor Wall x2 (Metal)",
   56: "Conveyor Wall x1 (Metal)",
   59: "Assembler",
   60: "U-Jelly Landing Pad",
   65: "AWESOME Sink",
   66: "AWESOME Shop",
   67: "Coal-Powered Generator",
   68: "Water Extractor",
   69: "Clean Pipeline Mk.1",
   70: "Pipeline Support",
   71: "Pipeline Junction",
   72: "Pipeline Pump Mk.1",
   73: "Fluid Buffer",
   74: "Conveyor Belt Mk.2",
   75: "Stackable Conveyor Pole",
   76: "Conveyor Lift Mk.2",
   77: "Truck Station",
   78: "Foundry",
   79: "Miner Mk.2",
   80: "Hypertube Entrance",
   81: "Hypertube",
   82: "Hypertube Support",
   83: "Stackable Hypertube Support",
   84: "Oil Extractor",
   85: "Refinery",
   86: "Valve",
   87: "Manufacturer",
   88: "Power Storage",
   89: "Industrial Storage Container",
   90: "Conveyor Belt Mk.3",
   91: "Conveyor Lift Mk.3",
   92: "Stackable Pipeline Support",
   93: "Packager",
   94: "Industrial Fluid Buffer",
   95: "Fuel-Powered Generator",
   96: "Conveyor Belt Mk.4",
   97: "Conveyor Lift Mk.4",
   98: "Railway",
   99: "N/A (Cheat Train Teleport Station)",
   100: "Freight Platform",
   101: "Fluid Freight Platform",
   102: "Empty Platform",
   103: "Clean Pipeline Mk.2",
   104: "Pipeline Pump Mk.2",
   105: "Blender",
   106: "Conveyor Belt Mk.5",
   107: "Conveyor Lift Mk.5",
   108: "Nuclear Power Plant",
   109: "Miner Mk.3",
   110: "Particle Accelerator",
   111: "Power Switch",
   112: "Power Pole Mk.3",
   113: "Programmable Splitter",
   114: "Geothermal Generator",
   115: "Radar Tower",
   116: "FICSMAS Candy Cane",
   117: "FICSMAS Snowman",
   118: "FICSMAS Gift Tree",
   119: "FICSMAS Snow Dispenser",
   120: "FICSMAS Wreath",
   121: "Quarter Pipe",
   122: "Inverted Quarter Pipe",
   123: "Inner Corner Quarter Pipe",
   124: "Inverted Inner Corner Quarter Pipe",
   125: "Outer Corner Quarter Pipe",
   127: "Up Corner Ramp (8m x 1m)",
   128: "Up Corner Ramp (8m x 2m)",
   129: "Up Corner Ramp (8m x 4m)",
   130: "Down Corner Ramp (8m x 1m)",
   131: "Down Corner Ramp (8m x 2m)",
   132: "Down Corner Ramp (8m x 4m)",
   141: "Big Metal Pillar",
   142: "Big Pillar Support",
   143: "Double Ramps (8m x 2m)",
   144: "Double Ramps (8m x 4m)",
   145: "Double Ramps (8m x 8m)",
   146: "Frame Foundation (8m x 4m)",
   147: "Glass Frame Foundation",
   148: "Hypertube Wall Support",
   149: "Hypertube Wall Hole",
   150: "Inverted Up Corner (8m x 1m)",
   151: "Inverted Up Corner (8m x 2m)",
   152: "Inverted Up Corner (8m x 4m)",
   153: "Inverted Down Corner (8m x 1m)",
   154: "Inverted Down Corner (8m x 2m)",
   155: "Inverted Down Corner (8m x 4m)",
   156: "Inverted Ramp (8m x 1m)",
   157: "Inverted Ramp (8m x 2m)",
   158: "Inverted Ramp (8m x 4m)",
   159: "Pipeline Wall Support",
   160: "Pipeline Wall Hole",
   161: "Street Light",
   162: "Wall Outlet Mk.1",
   163: "Double Wall Outlet Mk.1",
   164: "Wall Outlet Mk.3",
   165: "Double Wall Outlet Mk.3",
   166: "Single Window",
   167: "Frame Window",
   168: "Reinforced Window",
   360: "Empty Platform With Catwalk",
   376: "Conveyor Lift Floor Hole",
   377: "Pipeline Floor Hole",
   378: "Industrial Railing",
   379: "Straight Walkway",
   380: "Walkway Intersection",
   381: "Walkway T-Junction",
   382: "Walkway Ramp",
   383: "Basic Wall (4m) (Metal)",
   384: "Foundation (1m)",
   385: "Foundation (2m)",
   386: "Foundation (4m)",
   387: "Ramp (1m)",
   388: "Ramp (2m)",
   389: "Ramp (4m)",
   390: "Basic Wall (4m)",
   391: "Basic Wall (1m)",
   392: "Metal Beam",
   393: "Painted Beam",
   394: "Beam Support",
   395: "Beam Connector",
   396: "Beam Connector Double",
   397: "Small Billboard",
   398: "Large Billboard",
   399: "Straight Catwalk",
   400: "Catwalk Intersection",
   401: "Catwalk T-Junction",
   402: "Catwalk Corner",
   403: "Catwalk Ramp",
   404: "Catwalk Stairs",
   405: "Big Concrete Pillar",
   406: "Small Concrete Pillar",
   407: "Small Pillar Support",
   408: "Up Corner Ramp (1m)",
   409: "Up Corner Ramp (2m)",
   410: "Up Corner Ramp (4m)",
   411: "Down Corner Ramp (1m)",
   412: "Down Corner Ramp (2m)",
   413: "Down Corner Ramp (4m)",
   414: "Inverted Ramp Wall (1m)",
   415: "Inverted Ramp Wall (2m)",
   416: "Inverted Ramp Wall (4m)",
   417: "Inverted Ramp Wall (8m)",
   418: "Ramp Wall (1m)",
   419: "Ramp Wall (2m)",
   420: "Ramp Wall (4m)",
   421: "Ramp Wall (8m)",
   422: "Display Sign",
   423: "Portrait Sign",
   424: "Square Sign (1m)",
   425: "Square Sign (2m)",
   426: "Center Door Wall (Metal)",
   427: "Side Door Wall (Metal)",
   428: "Center Door Wall (Orange)",
   429: "Side Door Wall (Orange)",
   430: "Road Barrier",
   431: "Modern Railing",
   432: "Small Metal Pillar",
   433: "Double Ramp (2m)",
   434: "Double Ramp (4m)",
   435: "Double Ramp (8m)",
   436: "Big Frame Pillar",
   437: "Small Frame Pillar",
   438: "Full Frame Window",
   439: "Hex Frame Window",
   440: "Frame Floor",
   441: "Frame Foundation",
   442: "Frame Wall",
   443: "Frame Ramp",
   444: "Inverted Frame Ramp",
   445: "Gate Hole Wall",
   446: "Automated Gate",
   447: "Hazard Storage Box",
   448: "Inverted Up Corner (1m)",
   449: "Inverted Up Corner (2m)",
   450: "Inverted Up Corner (4m)",
   451: "Inverted Down Corner (1m)",
   452: "Inverted Down Corner (2m)",
   453: "Inverted Down Corner (4m)",
   454: "Inverted Ramp (1m)",
   455: "Inverted Ramp (2m)",
   456: "Inverted Ramp (4m)",
   457: "Label Sign (2m)",
   458: "Label Sign (3m)",
   459: "Label Sign (4m)",
   460: "Square Sign (0.5m)",
   461: "Medical Storage Box",
   462: "Roof Flat (Orange)",
   463: "Roof (1m) (Orange)",
   464: "Roof (2m) (Orange)",
   465: "Roof (4m) (Orange)",
   466: "Tilted Wall (4m) (Orange)",
   467: "Tilted Wall (8m) (Orange)",
   468: "Tilted Corner Wall (4m) (Orange)",
   469: "Tilted Corner Wall (8m) (Orange)",
   470: "Flat Roof (Window)",
   471: "Roof (1m) (Window)",
   472: "Roof (2m) (Window)",
   473: "Roof (4m) (Window)",
   474: "Flat Roof (Asphalt)",
   475: "Roof (1m) (Asphalt)",
   476: "Roof (2m) (Asphalt)",
   477: "Roof (4m) (Asphalt)",
   478: "Flat Roof (Tar)",
   479: "Roof (1m) (Tar)",
   480: "Roof (2m) (Tar)",
   481: "Roof (4m) (Tar)",
   482: "Basic Wall (1m) (Concrete)",
   483: "Basic Wall (4m) (Concrete)",
   484: "Conveyor Wall x1 (Concrete)",
   485: "Conveyor Wall x2 (Concrete)",
   486: "Conveyor Wall x3 (Concrete)",
   487: "Inverted Ramp Wall (1m) (Concrete)",
   488: "Inverted Ramp Wall (2m) (Concrete)",
   489: "Inverted Ramp Wall (4m) (Concrete)",
   490: "Inverted Ramp Wall (8m) (Concrete)",
   491: "Ramp Wall (1m) (Concrete)",
   492: "Ramp Wall (2m) (Concrete)",
   493: "Ramp Wall (4m) (Concrete)",
   494: "Ramp Wall (8m) (Concrete)",
   495: "Center Door Wall (Concrete)",
   496: "Side Door Wall (Concrete)",
   497: "Gate Hole Wall (Concrete)",
   498: "Tilted Wall (4m) (Concrete)",
   499: "Tilted Wall (8m) (Concrete)",
   500: "Tilted Corner Wall (4m) (Concrete)",
   501: "Tilted Corner Wall (8m) (Concrete)",
   502: "Single Window (Concrete)",
   503: "Frame Window (Concrete)",
   504: "Panel Window (Concrete)",
   505: "Reinforced Window (Concrete)",
   506: "Foundation (1m) (Polished Concrete)",
   507: "Foundation (2m) (Polished Concrete)",
   508: "Foundation (4m) (Polished Concrete)",
   509: "Ramp (1m) (Polished Concrete)",
   510: "Ramp (2m) (Polished Concrete)",
   511: "Ramp (4m) (Polished Concrete)",
   512: "Foundation (1m) (Concrete)",
   513: "Foundation (2m) (Concrete)",
   514: "Foundation (4m) (Concrete)",
   515: "Ramp (1m) (Concrete)",
   516: "Ramp (2m) (Concrete)",
   517: "Ramp (4m) (Concrete)",
   518: "Foundation (1m) (Metal)",
   519: "Foundation (2m) (Metal)",
   520: "Foundation (4m) (Metal)",
   521: "Ramp (1m) (Metal)",
   522: "Ramp (2m) (Metal)",
   523: "Ramp (4m) (Metal)",
   524: "Up Corner Ramp (1m) (Polished Concrete)",
   525: "Up Corner Ramp (2m) (Polished Concrete)",
   526: "Up Corner Ramp (4m) (Polished Concrete)",
   527: "Down Corner Ramp (1m) (Polished Concrete)",
   528: "Down Corner Ramp (2m) (Polished Concrete)",
   529: "Down Corner Ramp (4m) (Polished Concrete)",
   530: "Down Corner Ramp (1m) (Concrete)",
   531: "Down Corner Ramp (2m) (Concrete)",
   532: "Down Corner Ramp (4m) (Concrete)",
   533: "Up Corner Ramp (1m) (Concrete)",
   534: "Up Corner Ramp (2m) (Concrete)",
   535: "Up Corner Ramp (4m) (Concrete)",
   536: "Down Corner Ramp (1m) (Metal)",
   537: "Down Corner Ramp (2m) (Metal)",
   538: "Down Corner Ramp (4m) (Metal)",
   539: "Up Corner Ramp (1m) (Metal)",
   540: "Up Corner Ramp (2m) (Metal)",
   541: "Up Corner Ramp (4m) (Metal)",
   542: "Double Ramp (2m) (Polished Concrete)",
   543: "Double Ramp (4m) (Polished Concrete)",
   544: "Double Ramp (8m) (Polished Concrete)",
   545: "Double Ramp (2m) (Concrete)",
   546: "Double Ramp (4m) (Concrete)",
   547: "Double Ramp (8m) (Concrete)",
   548: "Double Ramp (2m) (Metal)",
   549: "Double Ramp (4m) (Metal)",
   550: "Double Ramp (8m) (Metal)",
   551: "Inverted Down Corner (1m) (Polished Concrete)",
   552: "Inverted Down Corner (2m) (Polished Concrete)",
   553: "Inverted Down Corner (4m) (Polished Concrete)",
   554: "Inverted Up Corner (1m) (Polished Concrete)",
   555: "Inverted Up Corner (2m) (Polished Concrete)",
   556: "Inverted Up Corner (4m) (Polished Concrete)",
   557: "Inverted Down Corner (1m) (Concrete)",
   558: "Inverted Down Corner (2m) (Concrete)",
   559: "Inverted Down Corner (4m) (Concrete)",
   560: "Inverted Up Corner (1m) (Concrete)",
   561: "Inverted Up Corner (2m) (Concrete)",
   562: "Inverted Up Corner (4m) (Concrete)",
   563: "Inverted Down Corner (1m) (Metal)",
   564: "Inverted Down Corner (2m) (Metal)",
   565: "Inverted Down Corner (4m) (Metal)",
   566: "Inverted Up Corner (1m) (Metal)",
   567: "Inverted Up Corner (2m) (Metal)",
   568: "Inverted Up Corner (4m) (Metal)",
   569: "Inverted Ramp (1m) (Polished Concrete)",
   570: "Inverted Ramp (2m) (Polished Concrete)",
   571: "Inverted Ramp (4m) (Polished Concrete)",
   572: "Inverted Ramp (1m) (Concrete)",
   573: "Inverted Ramp (2m) (Concrete)",
   574: "Inverted Ramp (4m) (Concrete)",
   575: "Inverted Ramp (1m) (Metal)",
   576: "Inverted Ramp (2m) (Metal)",
   577: "Inverted Ramp (4m) (Metal)",
   578: "Basic Wall (1m) (Metal)",
   579: "Inverted Ramp Wall (1m) (Metal)",
   580: "Inverted Ramp Wall (4m) (Metal)",
   581: "Inverted Ramp Wall (8m) (Metal)",
   582: "Ramp Wall (1m) (Metal)",
   583: "Ramp Wall (2m) (Metal)",
   584: "Ramp Wall (4m) (Metal)",
   585: "Ramp Wall (8m) (Metal)",
   586: "Gate Hole Wall (Metal)",
   587: "Tilted Wall (4m) (Metal)",
   588: "Tilted Wall (8m) (Metal)",
   589: "Tilted Corner Wall (4m) (Metal)",
   590: "Tilted Corner Wall (8m) (Metal)",
   591: "Single Window (Metal)",
   592: "Reinforced Window (Metal)",
   593: "Frame Window (Metal)",
   594: "Panel Window (Metal)",
   596: "Block Signal",
   597: "Path Signal",
   619: "Hypertube Floor Hole",
   620: "Foundation (1m) (Asphalt)",
   621: "Foundation (2m) (Asphalt)",
   622: "Foundation (4m) (Asphalt)",
   623: "Ramp (1m) (Asphalt)",
   624: "Ramp (2m) (Asphalt)",
   625: "Ramp (4m) (Asphalt)",
   626: "Down Corner Ramp (1m) (Asphalt)",
   627: "Down Corner Ramp (2m) (Asphalt)",
   628: "Down Corner Ramp (4m) (Asphalt)",
   629: "Up Corner Ramp (1m) (Asphalt)",
   630: "Up Corner Ramp (2m) (Asphalt)",
   631: "Up Corner Ramp (4m) (Asphalt)",
   632: "Double Ramp (2m) (Asphalt)",
   633: "Double Ramp (4m) (Asphalt)",
   634: "Double Ramp (8m) (Asphalt)",
   635: "Inverted Down Corner (1m) (Asphalt)",
   636: "Inverted Down Corner (2m) (Asphalt)",
   637: "Inverted Down Corner (4m) (Asphalt)",
   638: "Inverted Up Corner (1m) (Asphalt)",
   639: "Inverted Up Corner (2m) (Asphalt)",
   640: "Inverted Up Corner (4m) (Asphalt)",
   641: "Inverted Ramp (1m) (Asphalt)",
   642: "Inverted Ramp (2m) (Asphalt)",
   643: "Inverted Ramp (4m) (Asphalt)",
   664: "Pipeline Mk.1",
   665: "Pipeline Mk.2",
   666: "Tilted Concave Wall (4m) (Orange)",
   667: "Tilted Concave Wall (8m) (Orange)",
   668: "Tilted Concave Wall (4m) (Concrete)",
   669: "Tilted Concave Wall (8m) (Concrete)",
   670: "Tilted Concave Wall (4m) (Metal)",
   671: "Tilted Concave Wall (8m) (Metal)",
   688: "Inverted Outer Corner Quarter Pipe",
   689: "Half Foundation (1m)",
   690: "Half Foundation (2m)",
   691: "Half Foundation (3m)",
   692: "Inner Corner Extension (1m) (FICSIT)",
   693: "Inner Corner Extension (2m) (FICSIT)",
   694: "Inner Corner Extension (4m) (FICSIT)",
   695: "Outer Corner Extension (1m) (FICSIT)",
   696: "Outer Corner Extension (2m) (FICSIT)",
   697: "Outer Corner Extension (4m) (FICSIT)",
   698: "Inner Corner Roof (1m) (Orange)",
   699: "Inner Corner Roof (2m) (Orange)",
   700: "Inner Corner Roof (4m) (Orange)",
   701: "Outer Corner Roof (1m) (Orange)",
   702: "Outer Corner Roof (2m) (Orange)",
   703: "Outer Corner Roof (4m) (Orange)",
   704: "Inner Corner Extension (1m) (Asphalt)",
   705: "Inner Corner Extension (2m) (Asphalt)",
   706: "Inner Corner Extension (4m) (Asphalt)",
   707: "Outer Corner Extension (1m) (Asphalt)",
   708: "Outer Corner Extension (2m) (Asphalt)",
   709: "Outer Corner Extension (4m) (Asphalt)",
   710: "Inner Corner Extension (1m) (Concrete)",
   711: "Inner Corner Extension (2m) (Concrete)",
   712: "Inner Corner Extension (4m) (Concrete)",
   713: "Outer Corner Extension (1m) (Concrete)",
   714: "Outer Corner Extension (2m) (Concrete)",
   715: "Outer Corner Extension (4m) (Concrete)",
   716: "Inner Corner Extension (1m) (Grip)",
   717: "Inner Corner Extension (2m) (Grip)",
   718: "Inner Corner Extension (4m) (Grip)",
   719: "Outer Corner Extension (1m) (Grip)",
   720: "Outer Corner Extension (2m) (Grip)",
   721: "Outer Corner Extension (4m) (Grip)",
   722: "Inner Corner Extension (1m) (Polished Concrete)",
   723: "Inner Corner Extension (2m) (Polished Concrete)",
   724: "Inner Corner Extension (4m) (Polished Concrete)",
   725: "Outer Corner Extension (1m) (Polished Concrete)",
   726: "Outer Corner Extension (2m) (Polished Concrete)",
   727: "Outer Corner Extension (4m) (Polished Concrete)",
   728: "Half Foundation (1m) (Asphalt)",
   729: "Half Foundation (2m) (Asphalt)",
   730: "Half Foundation (4m) (Asphalt)",
   731: "Half Foundation (1m) (Concrete)",
   732: "Half Foundation (2m) (Concrete)",
   733: "Half Foundation (4m) (Concrete)",
   734: "Half Foundation (1m) (Grip)",
   735: "Half Foundation (2m) (Grip)",
   736: "Half Foundation (4m) (Grip)",
   737: "Half Foundation (1m) (Polished Concrete)",
   738: "Half Foundation (2m) (Polished Concrete)",
   739: "Half Foundation (4m) (Polished Concrete)",
   740: "Inverted Quarter Pipe (Asphalt)",
   741: "Inverted Inner Corner Quarter Pipe (Asphalt)",
   742: "Inverted Outer Corner Quarter Pipe (Asphalt)",
   743: "Quarter Pipe (Asphalt)",
   744: "Inner Corner Quarter Pipe (Asphalt)",
   745: "Outer Corner Quarter Pipe (Asphalt)",
   746: "Inverted Quarter Pipe (Polished Concrete)",
   747: "Inverted Inner Corner Quarter Pipe (Polished Concrete)",
   748: "Inverted Outer Corner Quarter Pipe (Polished Concrete)",
   749: "Quarter Pipe (Polished Concrete)",
   750: "Inner Corner Quarter Pipe (Polished Concrete)",
   751: "Outer Corner Quarter Pipe (Polished Concrete)",
   752: "Inverted Quarter Pipe (Concrete)",
   753: "Inverted Inner Corner Quarter Pipe (Concrete)",
   754: "Inverted Outer Corner Quarter Pipe (Concrete)",
   755: "Quarter Pipe (Concrete)",
   756: "Inner Corner Quarter Pipe (Concrete)",
   757: "Outer Corner Quarter Pipe (Concrete)",
   758: "Inverted Quarter Pipe (Grip)",
   759: "Inverted Inner Corner Quarter Pipe (Grip)",
   760: "Inverted Outer Corner Quarter Pipe (Grip)",
   761: "Quarter Pipe (Grip)",
   762: "Inner Corner Quarter Pipe (Grip)",
   763: "Outer Corner Quarter Pipe (Grip)",
   764: "Inner Corner Roof (1m) (Window)",
   765: "Inner Corner Roof (2m) (Window)",
   766: "Inner Corner Roof (4m) (Window)",
   767: "Outer Corner Roof (1m) (Window)",
   768: "Outer Corner Roof (2m) (Window)",
   769: "Outer Corner Roof (4m) (Window)",
   770: "Inner Corner Roof (1m) (Metal)",
   771: "Inner Corner Roof (2m) (Metal)",
   772: "Inner Corner Roof (4m) (Metal)",
   773: "Outer Corner Roof (1m) (Metal)",
   774: "Outer Corner Roof (2m) (Metal)",
   775: "Outer Corner Roof (4m) (Metal)",
   776: "Inner Corner Roof (1m) (Tar)",
   777: "Inner Corner Roof (2m) (Tar)",
   778: "Inner Corner Roof (4m) (Tar)",
   779: "Outer Corner Roof (1m) (Tar)",
   780: "Outer Corner Roof (2m) (Tar)",
   781: "Outer Corner Roof (4m) (Tar)",
   783: "Power Tower",
   784: "Power Tower Platform",
   785: "Priority Power Switch",
   786: "Blueprint Designer Mk.1",
   787: "Conveyor Wall Mount",
   788: "Conveyor Ceiling Mount",
   789: "Inverted Ramp Wall (2m) (Metal)",
   790: "Walkway Corner",
   791: "Main Portal",
   792: "Satellite Portal",
   793: "Conveyor Belt Mk.6",
   794: "Conveyor Lift Mk.6",
   795: "Quantum Encoder",
   796: "Converter",
   797: "Dimensional Depot Uploader",
   798: "Alien Power Augmenter",
   819: "Blueprint Designer Mk.3",
   820: "Blueprint Designer Mk.2",
   821: "Foundation (2m) (Concrete Polished)",
   822: "Foundation Stairs (1 m) (FICSIT)",
   823: "Foundation Stairs (2 m) (FICSIT)",
   824: "Foundation Stairs (4 m) (FICSIT)",
   825: "Foundation Stairs (1 m) (Asphalt)",
   826: "Foundation Stairs (2 m) (Asphalt)",
   827: "Foundation Stairs (4 m) (Asphalt)",
   828: "Foundation Stairs (1 m) (Polished Concrete)",
   829: "Foundation Stairs (2 m) (Polished Concrete)",
   830: "Foundation Stairs (4 m) (Polished Concrete)",
   831: "Foundation Stairs (1 m) (Concrete)",
   832: "Foundation Stairs (2 m) (Concrete)",
   833: "Foundation Stairs (4 m) (Concrete)",
   834: "Foundation Stairs (1 m) (Grip Metal)",
   835: "Foundation Stairs (2 m) (Grip Metal)",
   836: "Foundation Stairs (4 m) (Grip Metal)",
   837: "Honeycomb Frame Window",
   838: "Triple Frame Window",
   839: "Angled Frame Window",
   840: "Tarp Construction Fence",
   841: "Construction Fence",
   842: "Low Barrier",
   843: "High Barrier",
   860: "Hypertube Junction",
   861: "Hypertube Branch",
   862: "Roll-Up Gate (Steel)",
   863: "Roll-Up Gate (Orange)",
   864: "Roll-Up Gate (Concrete)",
   865: "Large Fan",
   866: "Large Vent",
   867: "Basic Shelf Unit",
   868: "Personnel Elevator",
   869: "Elevator Floor Stop",
   870: "Corner Road Barrier",
   871: "Conveyor Throughput Monitor",
   872: "Conveyor Wall Hole",
   873: "Braided Cable",
   874: "Braided Cable Cluster",
   875: "Round Concrete Beam",
   876: "H-Beam",
   877: "Shelf Beam",
   878: "FICSMAS Snow Cannon",
   879: "FICSMAS Power Light",
   880: "Priority Merger",
   881: "Buffer Stop",
   885: "Pipeline T-Junction",
   886: "SPWN",
   887: "Fluid Truck Station",
   889: "Explorer Vehicle Path",
   890: "Tractor Vehicle Path",
   891: "Universal Vehicle Path",
   892: "Truck Vehicle Path",
   893: "Cross Beam",
   894: "Factory Cart Vehicle Path",

   # Parts
   193: "Iron Ore",
   194: "Iron Ingot",
   195: "Iron Plate",
   196: "Iron Rod",
   198: "Copper Ore",
   199: "Bauxite",
   200: "Caterium Ore",
   201: "Uranium",
   202: "Crude Oil",
   203: "Sulfur",
   204: "Limestone",
   205: "Coal",
   206: "Raw Quartz",
   207: "Reinforced Iron Plate",
   208: "Cable",
   209: "Wire",
   210: "Copper Ingot",
   211: "Concrete",
   212: "Screw",
   213: "Wood",
   214: "Biomass",
   215: "Leaves",
   216: "FICSMAS Tree Branch",
   217: "FICSMAS Gift",
   218: "Quartz Crystal",
   219: "Steel Beam",
   220: "Copper Sheet",
   221: "Encased Industrial Beam",
   222: "Rubber",
   223: "Motor",
   224: "Plastic",
   225: "Heavy Modular Frame",
   226: "High-Speed Connector",
   227: "Alclad Aluminum Sheet",
   228: "Aluminum Casing",
   229: "Radio Control Unit",
   230: "AI Limiter",
   231: "Drone",
   232: "Rotor",
   233: "Modular Frame",
   235: "Empty Canister",
   236: "Petroleum Coke",
   237: "Steel Ingot",
   238: "Packaged Water",
   239: "Packaged Fuel",
   241: "Aluminum Scrap",
   243: "Circuit Board",
   244: "Versatile Framework",
   245: "Caterium Ingot",
   246: "Polymer Resin",
   247: "Stator",
   248: "Automated Wiring",
   249: "Smart Plating",
   250: "Fabric",
   251: "Aluminum Ingot",
   253: "Compacted Coal",
   255: "Packaged Turbofuel",
   256: "Steel Pipe",
   257: "Battery",
   258: "Heat Sink",
   259: "Cooling System",
   260: "Electromagnetic Control Rod",
   261: "Uranium Waste",
   262: "Nitric Acid",
   264: "Non-fissile Uranium",
   265: "Fused Modular Frame",
   266: "Encased Plutonium Cell",
   267: "Supercomputer",
   268: "Pressure Conversion Cube",
   269: "Plutonium Fuel Rod",
   270: "Crystal Oscillator",
   271: "Computer",
   272: "Packaged Nitrogen Gas",
   273: "Turbo Motor",
   274: "Quickwire",
   275: "Silica",
   276: "Black Powder",
   277: "Nobelisk",
   278: "Encased Uranium Cell",
   279: "Uranium Fuel Rod",
   280: "SAM Ore",
   281: "Power Shard",
   282: "Solid Biofuel",
   283: "Tractor",
   284: "Truck",
   285: "Modular Engine",
   286: "Adaptive Control Unit",
   287: "Packaged Oil",
   288: "Packaged Heavy Oil Residue",
   289: "Packaged Liquid Biofuel",
   291: "Electric Locomotive",
   292: "Freight Car",
   293: "Gas Filter",
   294: "Packaged Alumina Solution",
   295: "Iodine Infused Filter",
   296: "Packaged Sulfuric Acid",
   297: "Assembly Director System",
   298: "Magnetic Field Generator",
   299: "Empty Fluid Tank",
   300: "Thermal Propulsion Rocket",
   301: "Packaged Nitric Acid",
   302: "Plutonium Pellet",
   303: "Copper Powder",
   304: "Nuclear Pasta",
   305: "Hog Remains",
   307: "Plasma Spitter Remains",
   308: "Mycelia",
   311: "Blue Power Slug",
   312: "Yellow Power Slug",
   313: "Purple Power Slug",
   314: "Explorer",
   315: "Rifle Cartridge",
   316: "Candy Cane",
   317: "FICSMAS Bow",
   318: "FICSMAS Actual Snow",
   319: "Red FICSMAS Ornament",
   320: "Blue FICSMAS Ornament",
   321: "Copper FICSMAS Ornament",
   322: "Iron FICSMAS Ornament",
   323: "FICSMAS Ornament Bundle",
   324: "FICSMAS Decoration",
   325: "FICSMAS Wonder Star",
   326: "Snowball",
   327: "Cyber Wagon",
   646: "Sweet Fireworks",
   647: "Fancy Fireworks",
   648: "Sparkly Fireworks",
   672: "Alien Protein",
   673: "Iron Rebar",
   674: "Alien DNA Capsule",
   675: "Hatcher Remains",
   676: "Stinger Remains",
   677: "Stun Rebar",
   678: "Rifle Ammo",
   679: "Homing Rifle Ammo",
   680: "Gas Nobelisk",
   681: "Shatter Rebar",
   682: "Pulse Nobelisk",
   683: "Smokeless Powder",
   684: "Cluster Nobelisk",
   685: "Explosive Rebar",
   686: "Nuke Nobelisk",
   687: "Turbo Rifle Ammo",
   799: "SAM Fluctuator",
   800: "Superposition Oscillator",
   801: "Ficsite Trigon",
   802: "Rocket Fuel",
   803: "Packaged Ionized Fuel",
   804: "Dark Matter Crystal",
   805: "Singularity Cell",
   806: "Time Crystal",
   807: "Neural-Quantum Processor",
   808: "Ballistic Warp Drive",
   809: "SAM Ingot",
   810: "Diamonds",
   812: "AI Expansion Server",
   813: "Ficsite Ingot",
   814: "Biochemical Sculptor",
   815: "Plutonium Waste",
   816: "Mercer Sphere",
   817: "Somersloop",
   818: "Alien Power Matrix",
   844: "Excited Photonic Matter",
   845: "Dark Matter Residue",
   846: "Turbofuel",
   847: "Packaged Rocket Fuel",
   848: "Fuel",
   849: "Nitrogen Gas",
   851: "Ionized Fuel",
   852: "Water",
   853: "Heavy Oil Residue",
   854: "Liquid Biofuel",
   855: "Alumina Solution",
   856: "Sulfuric Acid",
   857: "Dissolved Silica",
   858: "Ficsonium",
   859: "Ficsonium Fuel Rod",
   888: "Fluid Truck",
   895: "FICSMAS Data Cartridge Day 14",

   # Equipment
   169: "Xeno-Zapper",
   170: "Portable Miner",
   172: "Blade Runners",
   173: "Object Scanner",
   174: "Nobelisk Detonator",
   175: "Chainsaw",
   176: "Xeno-Basher",
   177: "Jetpack",
   178: "Gas Mask",
   179: "Hazmat Suit",
   180: "Hover Pack",
   181: "Rebar Gun",
   182: "Medicinal Inhaler",
   183: "Zipline",
   185: "Parachute",
   186: "Bacon Agaric",
   187: "Paleberry",
   188: "Beryl Nut",
   189: "Rifle",
   190: "Candy Cane Basher (right)",
   191: "SnowballPile",
   192: "Factory Cart(TM)",
   884: "Candy Cane Basher (left)",

   # Other
   599: "Twirl Build Gun Emote",
   600: "Clap Emote",
   601: "Facepalm Emote",
   602: "Heart Emote",
   603: "Paper Emote",
   604: "Rock Emote",
   605: "Scissors Emote",
   606: "Point Emote",
   607: "Wave Emote",
   608: "Checkit",
   609: "Lizard Doggo",
   614: "FICSMAS Berries",
   615: "FICSMAS Check",
   616: "FICSMAS Checkit",
   617: "FICSMAS Gift (flat green)",

   # Explicitly Hidden
   15: "Wall Conveyor Perpendicular (Hidden)",
   27: "Game/Fence (Hidden)",
   37: "Remote Storage (Hidden)",
   44: "Wall 8m x 4m (Hidden)",
   57: "Stairs Left (Hidden)",
   58: "Stairs Right (Hidden)",
   133: "Center Door Wall (Hidden) [133]",
   134: "Left Door Wall (Hidden) [134]",
   135: "Right Door Wall (Hidden) [135]",
   136: "Center Door Wall (Hidden) [136]",
   137: "Left Door Wall (Hidden) [137]",
   138: "Right Door Wall (Hidden) [138]",
   139: "Gate Wall (Hidden)",
   171: "Beacon (Hidden)",
   184: "Game/ColorGun (Hidden)",
   197: "Parts/HUBParts (Hidden)",
   234: "Heavy Oil Residue (Hidden)",
   240: "Alumina Solution (Hidden)",
   242: "Water (Hidden)",
   252: "Fuel (Hidden)",
   254: "Turbofuel (Hidden)",
   263: "Sulfuric Acid (Hidden)",
   290: "Liquid Biofuel (Hidden)",
   306: "Game/SpikedRebar (Hidden)",
   310: "Color Cartridge (Hidden)",
   359: "Logistics/ConveyorLiftFloorHole (Hidden)",
   595: "Golden Factory Cart(TM) (Hidden)",
   811: "Dark Matter Crystal (Hidden)",
   850: "Supercomputer (Hidden)",
   882: "Beam Prototype 01 (Hidden)",
   883: "Inverted Concrete Foundation Convex 8x4 (Hidden)",

   # Not found in UI
   17: "Foundation Cheat Green",
   363: "Backgrounds/BlueprintGrid",
   364: "Backgrounds/Grid",
   365: "Backgrounds/Checkered",
   366: "Backgrounds/DiagonalLines",
   367: "Backgrounds/Dots",
   368: "Backgrounds/Rectangles",
   369: "Icons/None",
   370: "Backgrounds/Gradient/Radial",
   371: "Backgrounds/Wave",
   372: "Backgrounds/Gradient/Vertical",
   373: "Backgrounds/Gradient/Horizontal",
   374: "Icons/Checkmark",
   375: "Backgrounds/FICSIT",
   610: "FICSMAS/Backgrounds/Logo",
   611: "FICSMAS/Backgrounds/Snowflake",
   612: "FICSMAS/Backgrounds/CheckSnowflakes",
   613: "FICSMAS/Backgrounds/WrappingPaper",
   618: "FICSMAS/Backgrounds/UglySweater",
}

ICON_NAMES_TO_IDS = {}
for iconId in ICON_IDS_TO_NAMES:
   iconName = ICON_IDS_TO_NAMES[iconId]
   if iconName in ICON_NAMES_TO_IDS:
      print(f"Duplicate icon name '{iconName}'")
   else:
      ICON_NAMES_TO_IDS[iconName] = iconId

if __name__ == '__main__':
   import os
   import sys
   import json
   import readableNames

   ICON_LIBRARY_JSON = os.path.join(os.path.dirname(os.path.realpath(__file__)), "IconLibrary.uasset.json")
   if os.path.isfile(ICON_LIBRARY_JSON):
      with open(ICON_LIBRARY_JSON, "r") as fin:
         iconLibrary = json.load(fin)
         for library in iconLibrary:
            if "Name" in library and library["Name"] == "IconLibrary" and "Properties" in library and "mIconData" in library["Properties"]:
               iconData = library["Properties"]["mIconData"]
               for icon in iconData:
                  if "ID" in icon:
                     iconId = icon["ID"]

                     textureAssetPathName = None
                     iconDescPath = None
                     iconNameStr = None
                     iconNameKey = None

                     if "Texture" in icon and "AssetPathName" in icon["Texture"]:
                        textureAssetPathName = icon["Texture"]["AssetPathName"]
                     if "ItemDescriptor" in icon and "AssetPathName" in icon["ItemDescriptor"]:
                        iconDescPath = icon["ItemDescriptor"]["AssetPathName"]
                        if iconDescPath == "":
                           iconDescPath = None
                     if "IconName" in icon:
                        if "Key" in icon["IconName"]:
                           iconNameKey = icon["IconName"]["Key"]
                        if "CultureInvariantString" in icon["IconName"]:
                           iconNameStr = icon["IconName"]["CultureInvariantString"]

                     chosenName = None
                     if iconDescPath is not None:
                        pos = iconDescPath.rfind(".")
                        if pos != -1:
                           iconDescName = iconDescPath[pos+1:]
                           if iconDescName in readableNames.READABLE_PATH_NAME_CORRECTIONS:
                              chosenName = readableNames.READABLE_PATH_NAME_CORRECTIONS[iconDescName]
                           elif iconDescName.startswith("Desc_"):
                              iconDescName = iconDescName.replace("Desc_", "Build_")
                              if iconDescName in readableNames.READABLE_PATH_NAME_CORRECTIONS:
                                 chosenName = readableNames.READABLE_PATH_NAME_CORRECTIONS[iconDescName]
                        if chosenName is None:
                           chosenName = iconDescPath

                     elif iconNameKey is not None:
                        chosenName = iconNameKey
                     elif iconNameStr is not None:
                        chosenName = iconNameStr
                     elif textureAssetPathName is not None:
                        chosenName = textureAssetPathName

                     if "Hidden" in icon and icon["Hidden"]:
                        chosenName = chosenName + " (Hidden)"

                     if iconId not in ICON_IDS_TO_NAMES:
                        print(f'   {iconId}: "{chosenName}",')
               break
