READABLE_PATH_NAME_CORRECTIONS = {
   # Project Assembly Phases
   "GP_Project_Assembly_Phase_0": "Phase 0: Onboarding",
   "GP_Project_Assembly_Phase_1": "Phase 1: Distribution Platform",
   "GP_Project_Assembly_Phase_2": "Phase 2: Construction Dock",
   "GP_Project_Assembly_Phase_3": "Phase 3: Main Body",
   "GP_Project_Assembly_Phase_4": "Phase 4: Propulsion Systems",
   "GP_Project_Assembly_Phase_5": "Phase 5: Assembly",
   "GP_Project_Assembly_Phase_6": "Phase 6: Completing",
   "GP_Project_Assembly_Phase_7": "Phase 7: Completed",

   # Vehicles
   "BP_StartingPod_C": "Starting Pod",
   "BP_DroneTransport_C": "Drone",
   "BP_Explorer_C": "Explorer",
   "BP_FreightWagon_C": "Freight Car",
   "BP_Golfcart_C": "Factory Cart (TM)",
   "BP_GolfcartGold_C": "Factory Cart (Gold)",
   "BP_Locomotive_C": "Electric Locomotive",
   "BP_Tractor_C": "Tractor",
   "BP_Train_C": "Train",
   "BP_Truck_C": "Truck",
   "BP_VehicleTargetPoint_C": "Vehicle Target Point",
   "Testa_BP_WB_C": "Cyber Wagon",

   # Equipment
   "BP_EqDescZipLine_C": "Zipline",
   "BP_EquipmentDescriptorBeacon_C": "Beacon",
   "BP_EquipmentDescriptorBuildGun_C": "Build Gun",
   "BP_EquipmentDescriptorCandyCane_C": "Candy Cane Basher",
   "BP_EquipmentDescriptorCupGold_C": "'Employee of the Planet' Cup",
   "BP_EquipmentDescriptorCup_C": "Cup",
   "BP_EquipmentDescriptorGasmask_C": "Gas Mask",
   "BP_EquipmentDescriptorHazmatSuit_C": "Hazmat Suit",
   "BP_EquipmentDescriptorHoverPack_C": "Hover Pack",
   "BP_EquipmentDescriptorJetPack_C": "Jetpack",
   "BP_EquipmentDescriptorJumpingStilts_C": "Blade Runners",
   "BP_EquipmentDescriptorMachinegun_C": "Machine Gun",
   "BP_EquipmentDescriptorNobeliskDetonator_C": "Nobelisk Detonator",
   "BP_EquipmentDescriptorObjectScanner_C": "Object Scanner",
   "BP_EquipmentDescriptorResourceMiner_C": "Portable Miner",
   "BP_EquipmentDescriptorRifleMk2_C": "Rifle Mk.2",
   "BP_EquipmentDescriptorRifle_C": "Rifle",
   "BP_EquipmentDescriptorShockShank_C": "Xeno-Zapper",
   "BP_EquipmentDescriptorSnowballMittens_C": "Snowball Pile",
   "BP_EquipmentDescriptorStunSpear_C": "Xeno-Basher",
   "BP_ItemDescriptorPortableMiner_C": "Portable Miner",

   # Creatures
   "Desc_HogAlpha_C": "Alpha Hog",
   "Desc_HogBasic_C": "Fluffy-tailed Hog",
   "Desc_HogCliff_C": "Cliff Hog",
   "Desc_HogNuclear_C": "Radioactive Cliff Hog",
   "Desc_NonflyingBird_C": "Non-flying Bird",  # Technically "Non-flying Birb"
   "Desc_SpaceGiraffe_C": "Space Giraffe-Tick-Penguin-Whale Thing",
   "Desc_SpaceRabbit_C": "Lizard Doggo",
   "Desc_SpitterAquatic_Alpha_C": "Alpha Aquatic Spitter",
   "Desc_SpitterAquatic_Small_C": "Small Aquatic Spitter",
   "Desc_SpitterDesert_Alpha_C": "Alpha Desert Spitter",
   "Desc_SpitterDesert_Small_C": "Small Desert Spitter",
   "Desc_SpitterForest_Alpha_C": "Alpha Forest Spitter",
   "Desc_SpitterForest_Red_Alpha_C": "Alpha Red Forest Spitter",
   "Desc_SpitterForest_Small_C": "Small Forest Spitter",
   "Desc_SpitterForest_Small_Red_C": "Small Red Forest Spitter",
   "Desc_StingerAlpha_C": "Alpha Stinger",
   "Desc_StingerElite_C": "Gas Stinger",
   "Desc_StingerSmall_C": "Small Stinger",
   "Char_AlphaHog_C": "Alpha Hog",
   "Char_CliffHog_C": "Cliff Hog",
   "Char_CrabHatcher_C": "Flying Crab Hatchers",
   "Char_EliteStinger_C": "Gas Stinger",
   "Char_Hog_C": "Fluffy-tailed Hog",
   "Char_NonFlyingBird_C": "Non-flying Bird",  # Technically "Non-flying Birb"
   "Char_NuclearHog_C": "Radioactive Cliff Hog",
   "Char_SpaceGiraffe_C": "Space Giraffe-Tick-Penguin-Whale Thing",
   "Char_SpaceRabbit_C": "Lizard Doggo",
   "Char_SpitterAquaticAlpha_C": "Alpha Aquatic Spitter",
   "Char_SpitterAquaticSmall_C": "Small Aquatic Spitter",
   "Char_SpitterDesertAlpha_C": "Alpha Desert Spitter",
   "Char_SpitterDesertSmall_C": "Small Desert Spitter",
   "Char_SpitterForestAlpha_C": "Alpha Forest Spitter",
   "Char_SpitterForestRedAlpha_C": "Alpha Red Forest Spitter",
   "Char_SpitterForestRedSmall_C": "Small Red Forest Spitter",
   "Char_SpitterForestSmall_C": "Small Forest Spitter",
   "Char_Stinger_C": "Stinger",
   "Char_Stinger_Child_C": "Small Stinger",

   # Buildables
   "BP_ElevatorCabin_C": "Personnel Elevator Cabin",
   "BP_ProjectAssembly_C": "Space Elevator Terminal", # Not a separate item
   "BP_SoundTrigger_C": "Sound Trigger",
   "Build_AlienPowerBuilding_C": "Alien Power Augmenter",
   "Build_AssemblerMk1_C": "Assembler",
   "Build_Beam_C": "Metal Beam",
   "Build_Beam_Connector_C": "Beam Connector",
   "Build_Beam_Connector_Double_C": "Beam Connector Double",
   "Build_Beam_Painted_C": "Painted Beam",
   "Build_Beam_Support_C": "Beam Support",
   "Build_BigGarageDoor_16x8_C": "Roll-Up Gate",
   "Build_Blender_C": "Blender",
   "Build_BlueprintDesigner_C": "Blueprint Designer",
   "Build_BlueprintDesigner_MK2_C": "Blueprint Designer Mk.2",
   "Build_BlueprintDesigner_Mk3_C": "Blueprint Designer Mk.3",
   "Build_Blueprint_C": "Factory Blueprint",
   "Build_CI_C": "Collectable Indicator Config", # Mod: Collectable Indicator
   "Build_CandyCaneDecor_C": "Candy Cane",
   "Build_CatwalkCorner_C": "Catwalk Corner",
   "Build_CatwalkCross_C": "Catwalk Crossing",
   "Build_CatwalkRamp_C": "Catwalk Ramp",
   "Build_CatwalkStairs_C": "Catwalk Stairs",
   "Build_CatwalkStraight_C": "Catwalk Straight",
   "Build_CatwalkT_C": "Catwalk T-Crossing",
   "Build_CeilingLight_C": "Ceiling Light",
   "Build_CentralStorage_C": "Dimensional Depot Uploader",
   "Build_Concrete_Barrier_01_C": "Road Barrier",
   "Build_ConstructorMk1_C": "Constructor",
   "Build_Converter_C": "Converter",
   "Build_ConveyorAttachmentMergerPriority_C": "Priority Merger",
   "Build_ConveyorAttachmentMerger_C": "Conveyor Merger",
   "Build_ConveyorAttachmentSplitterProgrammable_C": "Programmable Splitter",
   "Build_ConveyorAttachmentSplitterSmart_C": "Smart Splitter",
   "Build_ConveyorAttachmentSplitter_C": "Conveyor Splitter",
   "Build_ConveyorBeltMk1_C": "Conveyor Belt Mk.1",
   "Build_ConveyorBeltMk2_C": "Conveyor Belt Mk.2",
   "Build_ConveyorBeltMk3_C": "Conveyor Belt Mk.3",
   "Build_ConveyorBeltMk4_C": "Conveyor Belt Mk.4",
   "Build_ConveyorBeltMk5_C": "Conveyor Belt Mk.5",
   "Build_ConveyorBeltMk6_C": "Conveyor Belt Mk.6",
   "Build_ConveyorCeilingAttachment_C": "Conveyor Ceiling Mount",
   "Build_ConveyorLiftMk1_C": "Conveyor Lift Mk.1",
   "Build_ConveyorLiftMk2_C": "Conveyor Lift Mk.2",
   "Build_ConveyorLiftMk3_C": "Conveyor Lift Mk.3",
   "Build_ConveyorLiftMk4_C": "Conveyor Lift Mk.4",
   "Build_ConveyorLiftMk5_C": "Conveyor Lift Mk.5",
   "Build_ConveyorLiftMk6_C": "Conveyor Lift Mk.6",
   "Build_ConveyorMonitor_C": "Conveyor Throughput Monitor",
   "Build_ConveyorPoleStackable_C": "Stackable Conveyor Pole",
   "Build_ConveyorPoleWall_C": "Conveyor Wall Mount",
   "Build_ConveyorPole_C": "Conveyor Pole",
   "Build_ConveyorWallHole_C": "Conveyor Wall Hole",
   "Build_DownQuarterPipeInCorner_Asphalt_8x4_C": "Inverted Inner Corner Quarter Pipe (Asphalt)",
   "Build_DownQuarterPipeInCorner_ConcretePolished_8x4_C": "Inverted Inner Corner Quarter Pipe (Polished Concrete)",
   "Build_DownQuarterPipeInCorner_Concrete_8x4_C": "Inverted Inner Corner Quarter Pipe (Concrete)",
   "Build_DownQuarterPipeInCorner_Grip_8x4_C": "Inverted Inner Corner Quarter Pipe (Grip)",
   "Build_DownQuarterPipeOutCorner_Asphalt_8x4_C": "Inverted Outer Corner Quarter Pipe (Asphalt)",
   "Build_DownQuarterPipeOutCorner_ConcretePolished_8x4_C": "Inverted Outer Corner Quarter Pipe (Polished Concrete)",
   "Build_DownQuarterPipeOutCorner_Concrete_8x4_C": "Inverted Outer Corner Quarter Pipe (Concrete)",
   "Build_DownQuarterPipeOutCorner_Grip_8x4_C": "Inverted Outer Corner Quarter Pipe (Grip)",
   "Build_DownQuarterPipe_Asphalt_8x4_C": "Inverted Quarter Pipe (Asphalt)",
   "Build_DownQuarterPipe_ConcretePolished_8x4_C": "Inverted Quarter Pipe (Polished Concrete)",
   "Build_DownQuarterPipe_Concrete_8x4_C": "Inverted Quarter Pipe (Concrete)",
   "Build_DownQuarterPipe_Grip_8x4_C": "Inverted Quarter Pipe (Grip)",
   "Build_DroneStation_C": "Drone Port",
   "Build_ElevatorFloorStop_C": "Elevator Floor Stop",
   "Build_Elevator_C": "Personnel Elevator",
   "Build_Fence_01_C": "Industrial Railing",
   "Build_Flat_Frame_01_C": "Frame Floor",
   "Build_FloodlightPole_C": "Flood Light Tower",
   "Build_FloodlightWall_C": "Wall Mounted Flood Light",
   "Build_FoundationGlass_01_C": "Glass Frame Foundation",
   "Build_FoundationPassthrough_Hypertube_C": "Hypertube Floor Hole",
   "Build_FoundationPassthrough_Lift_C": "Conveyor Lift Floor Hole",
   "Build_FoundationPassthrough_Pipe_C": "Pipeline Floor Hole",
   "Build_Foundation_8x1_01_C": "Foundation 1m",
   "Build_Foundation_8x2_01_C": "Foundation 2m",
   "Build_Foundation_8x4_01_C": "Foundation 4m",
   "Build_Foundation_Asphalt_8x1_C": "Foundation 1m (Asphalt)",
   "Build_Foundation_Asphalt_8x2_C": "Foundation 2m (Asphalt)",
   "Build_Foundation_Asphalt_8x4_C": "Foundation 4m (Asphalt)",
   "Build_Foundation_ConcretePolished_8x1_C": "Foundation 1m (Polished Concrete)",
   "Build_Foundation_ConcretePolished_8x2_2_C": "Foundation 2m (Polished Concrete)",
   "Build_Foundation_ConcretePolished_8x4_C": "Foundation 4m (Polished Concrete)",
   "Build_Foundation_Concrete_8x1_C": "Foundation 1m (Concrete)",
   "Build_Foundation_Concrete_8x2_C": "Foundation 2m (Concrete)",
   "Build_Foundation_Concrete_8x4_C": "Foundation 4m (Concrete)",
   "Build_Foundation_Frame_01_C": "Frame Foundation",
   "Build_Foundation_Metal_8x1_C": "Foundation 1m (Metal)",
   "Build_Foundation_Metal_8x2_C": "Foundation 2m (Metal)",
   "Build_Foundation_Metal_8x4_C": "Foundation 4m (Metal)",
   "Build_FoundryMk1_C": "Foundry",
   "Build_FrackingExtractor_C": "Resource Well Extractor",
   "Build_FrackingSmasher_C": "Resource Well Pressurizer",
   "Build_Gate_Automated_8x4_C": "Automated Gate",
   "Build_GeneratorBiomass_Automated_C": "Biomass Burner",
   "Build_GeneratorBiomass_C": "Biomass Burner (without input)",
   "Build_GeneratorCoal_C": "Coal Generator",
   "Build_GeneratorFuel_C": "Fuel Generator",
   "Build_GeneratorGeoThermal_C": "Geothermal Generator",
   "Build_GeneratorIntegratedBiomass_C": "Biomass Burner",
   "Build_GeneratorNuclear_C": "Nuclear Power Plant",
   "Build_GlassTank_4Pipes_C": "Industrial Glass Fluid Buffer 4 pipes", # Mod: Glass Fluid Buffer
   "Build_GlassTank_C": "Industrial Glass Fluid Buffer", # Mod: Glass Fluid Buffer
   "Build_GlassTank_Child_C": "Glass Fluid Buffer", # Mod: Glass Fluid Buffer
   "Build_GlassTank_Child_Child_C": "Glass Fluid Buffer 4 pipes", # Mod: Glass Fluid Buffer
   "Build_HadronCollider_C": "Particle Accelerator",
   "Build_HubTerminal_C": "HUB Terminal",
   "Build_HyperPoleStackable_C": "Stackable Hypertube Support",
   "Build_HyperTubeJunction_C": "Hypertube Junction",
   "Build_HypertubeTJunction_C": "Hypertube Branch",
   "Build_HyperTubeWallHole_C": "Hypertube Wall Hole",
   "Build_HyperTubeWallSupport_C": "Hypertube Wall Support",
   "Build_IndustrialTank_C": "Industrial Fluid Buffer",
   "Build_InvertedRamp_Asphalt_8x1_C": "Inv. Ramp 1m (Asphalt)",
   "Build_InvertedRamp_Asphalt_8x2_C": "Inv. Ramp 2m (Asphalt)",
   "Build_InvertedRamp_Asphalt_8x4_C": "Inv. Ramp 4m (Asphalt)",
   "Build_InvertedRamp_Concrete_8x1_C": "Inv. Ramp 1m (Concrete)",
   "Build_InvertedRamp_Concrete_8x2_C": "Inv. Ramp 2m (Concrete)",
   "Build_InvertedRamp_Concrete_8x4_C": "Inv. Ramp 4m (Concrete)",
   "Build_InvertedRamp_DCorner_Asphalt_8x1_C": "Inv. Down Corner 1m (Asphalt)",
   "Build_InvertedRamp_DCorner_Asphalt_8x2_C": "Inv. Down Corner 2m (Asphalt)",
   "Build_InvertedRamp_DCorner_Asphalt_8x4_C": "Inv. Down Corner 4m (Asphalt)",
   "Build_InvertedRamp_DCorner_Concrete_8x1_C": "Inv. Down Corner 1m (Concrete)",
   "Build_InvertedRamp_DCorner_Concrete_8x2_C": "Inv. Down Corner 2m (Concrete)",
   "Build_InvertedRamp_DCorner_Concrete_8x4_C": "Inv. Down Corner 4m (Concrete)",
   "Build_InvertedRamp_DCorner_Metal_8x1_C": "Inv. Down Corner 1m (Metal)",
   "Build_InvertedRamp_DCorner_Metal_8x2_C": "Inv. Down Corner 2m (Metal)",
   "Build_InvertedRamp_DCorner_Metal_8x4_C": "Inv. Down Corner 4m (Metal)",
   "Build_InvertedRamp_DCorner_Polished_8x1_C": "Inv. Down Corner 1m (Polished)",
   "Build_InvertedRamp_DCorner_Polished_8x2_C": "Inv. Down Corner 2m (Polished)",
   "Build_InvertedRamp_DCorner_Polished_8x4_C": "Inv. Down Corner 4m (Polished)",
   "Build_InvertedRamp_Metal_8x1_C": "Inv. Ramp 1m (Metal)",
   "Build_InvertedRamp_Metal_8x2_C": "Inv. Ramp 2m (Metal)",
   "Build_InvertedRamp_Metal_8x4_C": "Inv. Ramp 4m (Metal)",
   "Build_InvertedRamp_Polished_8x1_C": "Inv. Ramp 1m (Polished)",
   "Build_InvertedRamp_Polished_8x2_C": "Inv. Ramp 2m (Polished)",
   "Build_InvertedRamp_Polished_8x4_C": "Inv. Ramp 4m (Polished)",
   "Build_InvertedRamp_UCorner_Asphalt_8x1_C": "Inv. Up Corner 1m (Asphalt)",
   "Build_InvertedRamp_UCorner_Asphalt_8x2_C": "Inv. Up Corner 2m (Asphalt)",
   "Build_InvertedRamp_UCorner_Asphalt_8x4_C": "Inv. Up Corner 4m (Asphalt)",
   "Build_InvertedRamp_UCorner_Concrete_8x1_C": "Inv. Up Corner 1m (Concrete)",
   "Build_InvertedRamp_UCorner_Concrete_8x2_C": "Inv. Up Corner 2m (Concrete)",
   "Build_InvertedRamp_UCorner_Concrete_8x4_C": "Inv. Up Corner 4m (Concrete)",
   "Build_InvertedRamp_UCorner_Metal_8x1_C": "Inv. Up Corner 1m (Metal)",
   "Build_InvertedRamp_UCorner_Metal_8x2_C": "Inv. Up Corner 2m (Metal)",
   "Build_InvertedRamp_UCorner_Metal_8x4_C": "Inv. Up Corner 4m (Metal)",
   "Build_InvertedRamp_UCorner_Polished_8x1_C": "Inv. Up Corner 1m (Polished)",
   "Build_InvertedRamp_UCorner_Polished_8x2_C": "Inv. Up Corner 2m (Polished)",
   "Build_InvertedRamp_UCorner_Polished_8x4_C": "Inv. Up Corner 4m (Polished)",
   "Build_JumpPadAdjustable_C": "Jump Pad",
   "Build_Ladder_C": "Ladder",
   "Build_LandingPad_C": "U-Jelly Landing Pad",
   "Build_LightsControlPanel_C": "Lights Control Panel",
   "Build_LookoutTower_C": "Lookout Tower",
   "Build_Mam_C": "MAM",
   "Build_ManufacturerMk1_C": "Manufacturer",
   "Build_MF_C": "Multidimensional Factory", # Mod: Multidimensional Factory
   "Build_MinerMk1_C": "Miner Mk.1",
   "Build_MinerMk2_C": "Miner Mk.2",
   "Build_MinerMk3_C": "Miner Mk.3",
   "Build_Mk2Tube_C": "Hypertube Entrance Mk.2", # Mod: BetterHypertybes
   "Build_ModularLoadBalancer_Block_C": "Block Module", # Mod: Modular Load Balancers
   "Build_ModularLoadBalancer_Box_C": "Modular Load Balancer Box", # Mod: Modular Load Balancers
   "Build_ModularLoadBalancer_C": "Modular Load Balancer", # Mod: Modular Load Balancers
   "Build_ModularLoadBalancer_Filtered_C": "Filter Module", # Mod: Modular Load Balancers
   "Build_ModularLoadBalancer_Filtered_Output_C": "Output Only Filter Module", # Mod: Modular Load Balancers
   "Build_ModularLoadBalancer_Input_C": "Input Only Module", # Mod: Modular Load Balancers
   "Build_ModularLoadBalancer_Output_C": "Output Only Module", # Mod: Modular Load Balancers
   "Build_ModularLoadBalancer_Overflow_C": "Overflow Module", # Mod: Modular Load Balancers
   "Build_ModularLoadBalancer_Overflow_Output_C": "Output Only Overflow Module", # Mod: Modular Load Balancers
   "Build_ModularLoadBalancer_Programmable_C": "Programmable Module", # Mod: Modular Load Balancers
   "Build_ModularLoadBalancer_Programmable_Output_C": "Output Only Programmable Module", # Mod: Modular Load Balancers
   "Build_OilPump_C": "Oil Extractor",
   "Build_OilRefinery_C": "Refinery",
   "Build_Overlow1_C": "Dimensional Upload Priority", # Mod: Depot Uploader with Output
   "Build_Overlow_C": "Dimensional Overflow Priority", # Mod: Depot Uploader with Output
   "Build_Packager_C": "Packager",
   "Build_PillarBase_C": "Big Pillar Support",
   "Build_PillarBase_Small_C": "Small Pillar Support",
   "Build_PillarMiddle_C": "Big Metal Pillar",
   "Build_PillarMiddle_Concrete_C": "Big Concrete Pillar",
   "Build_PillarMiddle_Frame_C": "Big Frame Pillar",
   "Build_PillarTop_C": "Pillar Top",
   "Build_Pillar_Small_Concrete_C": "Small Concrete Pillar",
   "Build_Pillar_Small_Frame_C": "Small Frame Pillar",
   "Build_Pillar_Small_Metal_C": "Small Metal Pillar",
   "Build_PipeHyperStart_C": "Hypertube Entrance",
   "Build_PipeHyperSupport_C": "Hypertube Support",
   "Build_PipeHyper_C": "Hypertube",
   "Build_PipeStorageTank_C": "Fluid Buffer",
   "Build_PipeSupportStackable_C": "Stackable Pipeline Support",
   "Build_PipelineFlowIndicator_C": "Pipeline Flow Indicator",  # Part of a Pipeline
   "Build_PipelineJunction_Cross_C": "Pipeline Junction Cross",
   "Build_PipelineMK2_C": "Pipeline Mk.2",
   "Build_PipelineMK2_NoIndicator_C": "Pipeline Mk.2 (No Indicator)",
   "Build_PipelinePumpMk2_C": "Pipeline Pump Mk.2",
   "Build_PipelinePump_C": "Pipeline Pump Mk.1",
   "Build_PipelineSupportWallHole_C": "Pipeline Wall Hole",
   "Build_PipelineSupportWall_C": "Pipeline Wall Support",
   "Build_PipelineSupport_C": "Pipeline Support",
   "Build_Pipeline_C": "Pipeline Mk.1",
   "Build_Pipeline_NoIndicator_C": "Pipeline Mk.1 (No Indicator)",
   "Build_Portal_C": "Main Portal",
   "Build_PortalSatellite_C": "Satellite Portal",
   "BUILD_Potty_mk1_C": "The HUB Toilet",
   "Build_PowerLine_C": "Power Line",
   "Build_PowerPoleMk1_C": "Power Pole Mk.1",
   "Build_PowerPoleMk2_C": "Power Pole Mk.2",
   "Build_PowerPoleMk3_C": "Power Pole Mk.3",
   "Build_PowerPoleWallDouble_C": "Double Wall Outlet Mk.1",
   "Build_PowerPoleWallDouble_Mk2_C": "Double Wall Outlet Mk.2",
   "Build_PowerPoleWallDouble_Mk3_C": "Double Wall Outlet Mk.3",
   "Build_PowerPoleWall_C": "Wall Outlet Mk.1",
   "Build_PowerPoleWall_Mk2_C": "Wall Outlet Mk.2",
   "Build_PowerPoleWall_Mk3_C": "Wall Outlet Mk.3",
   "Build_PowerStorageMk1_C": "Power Storage",
   "Build_PowerSwitch_C": "Power Switch",
   "Build_PowerTowerPlatform_C": "Power Tower Platform",
   "Build_PowerTower_C": "Power Tower",
   "Build_PriorityPowerSwitch_C": "Priority Power Switch",
   "Build_QuantumEncoder_C": "Quantum Encoder",
   "Build_QuarterPipeCorner_01_C": "Inner Corner Quarter Pipe",
   "Build_QuarterPipeCorner_02_C": "Inverted Inner Corner Quarter Pipe",
   "Build_QuarterPipeCorner_03_C": "Outer Corner Quarter Pipe",
   "Build_QuarterPipeCorner_04_C": "Inverted Outer Corner Quarter Pipe",
   "Build_QuarterPipeInCorner_Asphalt_8x4_C": "Inner Corner Quarter Pipe (Asphalt)",
   "Build_QuarterPipeInCorner_ConcretePolished_8x4_C": "Inner Corner Quarter Pipe (Polished Concrete)",
   "Build_QuarterPipeInCorner_Concrete_8x4_C": "Inner Corner Quarter Pipe (Concrete)",
   "Build_QuarterPipeInCorner_Grip_8x4_C": "Inner Corner Quarter Pipe (Grip)",
   "Build_QuarterPipeMiddleInCorner_Asphalt_8x1_C": "Inner Corner Extension 1m (Asphalt)",
   "Build_QuarterPipeMiddleInCorner_Asphalt_8x2_C": "Inner Corner Extension 2m (Asphalt)",
   "Build_QuarterPipeMiddleInCorner_Asphalt_8x4_C": "Inner Corner Extension 4m (Asphalt)",
   "Build_QuarterPipeMiddleInCorner_Concrete_8x1_C": "Inner Corner Extension 1m (Concrete)",
   "Build_QuarterPipeMiddleInCorner_Concrete_8x2_C": "Inner Corner Extension 2m (Concrete)",
   "Build_QuarterPipeMiddleInCorner_Concrete_8x4_C": "Inner Corner Extension 4m (Concrete)",
   "Build_QuarterPipeMiddleInCorner_Ficsit_8x1_C": "Inner Corner Extension 1m (FICSIT)",
   "Build_QuarterPipeMiddleInCorner_Ficsit_8x2_C": "Inner Corner Extension 2m (FICSIT)",
   "Build_QuarterPipeMiddleInCorner_Ficsit_8x4_C": "Inner Corner Extension 4m (FICSIT)",
   "Build_QuarterPipeMiddleInCorner_Grip_8x1_C": "Inner Corner Extension 1m (Grip)",
   "Build_QuarterPipeMiddleInCorner_Grip_8x2_C": "Inner Corner Extension 2m (Grip)",
   "Build_QuarterPipeMiddleInCorner_Grip_8x4_C": "Inner Corner Extension 4m (Grip)",
   "Build_QuarterPipeMiddleInCorner_PolishedConcrete_8x1_C": "Inner Corner Extension 1m (Polished Concrete)",
   "Build_QuarterPipeMiddleInCorner_PolishedConcrete_8x2_C": "Inner Corner Extension 2m (Polished Concrete)",
   "Build_QuarterPipeMiddleInCorner_PolishedConcrete_8x4_C": "Inner Corner Extension 4m (Polished Concrete)",
   "Build_QuarterPipeMiddleOutCorner_Asphalt_4x1_C": "Outer Corner Extension 1m (Asphalt)",
   "Build_QuarterPipeMiddleOutCorner_Asphalt_4x2_C": "Outer Corner Extension 2m (Asphalt)",
   "Build_QuarterPipeMiddleOutCorner_Asphalt_4x4_C": "Outer Corner Extension 4m (Asphalt)",
   "Build_QuarterPipeMiddleOutCorner_Concrete_4x1_C": "Outer Corner Extension 1m (Concrete)",
   "Build_QuarterPipeMiddleOutCorner_Concrete_4x2_C": "Outer Corner Extension 2m (Concrete)",
   "Build_QuarterPipeMiddleOutCorner_Concrete_4x4_C": "Outer Corner Extension 4m (Concrete)",
   "Build_QuarterPipeMiddleOutCorner_Ficsit_4x1_C": "Outer Corner Extension 1m (FICSIT)",
   "Build_QuarterPipeMiddleOutCorner_Ficsit_4x2_C": "Outer Corner Extension 2m (FICSIT)",
   "Build_QuarterPipeMiddleOutCorner_Ficsit_4x4_C": "Outer Corner Extension 4m (FICSIT)",
   "Build_QuarterPipeMiddleOutCorner_Grip_4x1_C": "Outer Corner Extension 1m (Grip)",
   "Build_QuarterPipeMiddleOutCorner_Grip_4x2_C": "Outer Corner Extension 2m (Grip)",
   "Build_QuarterPipeMiddleOutCorner_Grip_4x4_C": "Outer Corner Extension 4m (Grip)",
   "Build_QuarterPipeMiddleOutCorner_PolishedConcrete_4x1_C": "Outer Corner Extension 1m (Polished Concrete)",
   "Build_QuarterPipeMiddleOutCorner_PolishedConcrete_4x2_C": "Outer Corner Extension 2m (Polished Concrete)",
   "Build_QuarterPipeMiddleOutCorner_PolishedConcrete_4x4_C": "Outer Corner Extension 4m (Polished Concrete)",
   "Build_QuarterPipeMiddle_Asphalt_8x1_C": "Half 1m Foundation (Asphalt)",
   "Build_QuarterPipeMiddle_Asphalt_8x2_C": "Half 2m Foundation (Asphalt)",
   "Build_QuarterPipeMiddle_Asphalt_8x4_C": "Half 4m Foundation (Asphalt)",
   "Build_QuarterPipeMiddle_Concrete_8x1_C": "Half 1m Foundation (Concrete)",
   "Build_QuarterPipeMiddle_Concrete_8x2_C": "Half 2m Foundation (Concrete)",
   "Build_QuarterPipeMiddle_Concrete_8x4_C": "Half 4m Foundation (Concrete)",
   "Build_QuarterPipeMiddle_Ficsit_8x1_C": "Half 1m Foundation (FICSIT)",
   "Build_QuarterPipeMiddle_Ficsit_8x2_C": "Half 2m Foundation (FICSIT)",
   "Build_QuarterPipeMiddle_Ficsit_8x4_C": "Half 4m Foundation (FICSIT)",
   "Build_QuarterPipeMiddle_Grip_8x1_C": "Half 1m Foundation (Grip)",
   "Build_QuarterPipeMiddle_Grip_8x2_C": "Half 2m Foundation (Grip)",
   "Build_QuarterPipeMiddle_Grip_8x4_C": "Half 4m Foundation (Grip)",
   "Build_QuarterPipeMiddle_PolishedConcrete_8x1_C": "Half 1m Foundation (Polished Concrete)",
   "Build_QuarterPipeMiddle_PolishedConcrete_8x2_C": "Half 2m Foundation (Polished Concrete)",
   "Build_QuarterPipeMiddle_PolishedConcrete_8x4_C": "Half 4m Foundation (Polished Concrete)",
   "Build_QuarterPipeOutCorner_Asphalt_8x4_C": "Outer Corner Quarter Pipe (Asphalt)",
   "Build_QuarterPipeOutCorner_ConcretePolished_8x4_C": "Outer Corner Quarter Pipe (Polished Concrete)",
   "Build_QuarterPipeOutCorner_Concrete_8x4_C": "Outer Corner Quarter Pipe (Concrete)",
   "Build_QuarterPipeOutCorner_Grip_8x4_C": "Outer Corner Quarter Pipe (Grip)",
   "Build_QuarterPipe_02_C": "Inverted Quarter Pipe",
   "Build_QuarterPipe_Asphalt_8x4_C": "Quarter Pipe (Asphalt)",
   "Build_QuarterPipe_C": "Quarter Pipe",
   "Build_QuarterPipe_ConcretePolished_8x4_C": "Quarter Pipe (Polished Concrete)",
   "Build_QuarterPipe_Concrete_8x4_C": "Quarter Pipe (Concrete)",
   "Build_QuarterPipe_Grip_8x4_C": "Quarter Pipe (Grip)",
   "Build_RadarTower_C": "Radar Tower",
   "Build_Railing_01_C": "Modern Railing",
   "Build_RailroadBlockSignal_C": "Block Signal",
   "Build_RailroadEndStop_C": "Buffer Stop (Railway Transport)",
   "Build_RailroadPathSignal_C": "Path Signal",
   "Build_RailroadSwitchControl_C": "Railroad Switch Control",
   "Build_RailroadTrackIntegrated_C": "Integrated Platform Track",
   "Build_RailroadTrack_C": "Railway",
   "Build_RampDouble_8x1_C": "Double Ramp 2m",
   "Build_RampDouble_Asphalt_8x1_C": "Double Ramp 2m (Asphalt)",
   "Build_RampDouble_Asphalt_8x2_C": "Double Ramp 4m (Asphalt)",
   "Build_RampDouble_Asphalt_8x4_C": "Double Ramp 8m (Asphalt)",
   "Build_RampDouble_C": "Double Ramp 4m",
   "Build_RampDouble_Concrete_8x1_C": "Double Ramp 2m (Concrete)",
   "Build_RampDouble_Concrete_8x2_C": "Double Ramp 4m (Concrete)",
   "Build_RampDouble_Concrete_8x4_C": "Double Ramp 8m (Concrete)",
   "Build_RampDouble_Metal_8x1_C": "Double Ramp 2m (Metal)",
   "Build_RampDouble_Metal_8x2_C": "Double Ramp 4m (Metal)",
   "Build_RampDouble_Metal_8x4_C": "Double Ramp 8m (Metal)",
   "Build_RampDouble_Polished_8x1_C": "Double Ramp 2m (Polished)",
   "Build_RampDouble_Polished_8x2_C": "Double Ramp 4m (Polished)",
   "Build_RampDouble_Polished_8x4_C": "Double Ramp 8m (Polished)",
   "Build_RampInverted_8x1_C": "Inv. Ramp 1m",
   "Build_RampInverted_8x1_Corner_01_C": "Inv. Up Corner 1m",
   "Build_RampInverted_8x1_Corner_02_C": "Inv. Down Corner 1m",
   "Build_RampInverted_8x2_01_C": "Inv. Ramp 2m",
   "Build_RampInverted_8x2_Corner_01_C": "Inv. Up Corner 2m",
   "Build_RampInverted_8x2_Corner_02_C": "Inv. Down Corner 2m",
   "Build_RampInverted_8x4_Corner_01_C": "Inv. Up Corner 4m",
   "Build_RampInverted_8x4_Corner_02_C": "Inv. Down Corner 4m",
   "Build_Ramp_8x1_01_C": "Ramp 1m",
   "Build_Ramp_8x2_01_C": "Ramp 2m",
   "Build_Ramp_8x4_01_C": "Ramp 4m",
   "Build_Ramp_8x4_Inverted_01_C": "Inv. Ramp 4m",
   "Build_Ramp_8x8x8_C": "Double Ramp 8m",
   "Build_Ramp_Asphalt_8x1_C": "Ramp 1m (Asphalt)",
   "Build_Ramp_Asphalt_8x2_C": "Ramp 2m (Asphalt)",
   "Build_Ramp_Asphalt_8x4_C": "Ramp 4m (Asphalt)",
   "Build_Ramp_Concrete_8x1_C": "Ramp 1m (Concrete)",
   "Build_Ramp_Concrete_8x2_C": "Ramp 2m (Concrete)",
   "Build_Ramp_Concrete_8x4_C": "Ramp 4m (Concrete)",
   "Build_Ramp_Diagonal_8x1_01_C": "Down Corner Ramp 1m",
   "Build_Ramp_Diagonal_8x1_02_C": "Up Corner Ramp 1m",
   "Build_Ramp_Diagonal_8x2_01_C": "Down Corner Ramp 2m",
   "Build_Ramp_Diagonal_8x2_02_C": "Up Corner Ramp 2m",
   "Build_Ramp_Diagonal_8x4_01_C": "Down Corner Ramp 4m",
   "Build_Ramp_Diagonal_8x4_02_C": "Up Corner Ramp 4m",
   "Build_Ramp_DownCorner_Asphalt_8x1_C": "Down Corner Ramp 1m (Asphalt)",
   "Build_Ramp_DownCorner_Asphalt_8x2_C": "Down Corner Ramp 2m (Asphalt)",
   "Build_Ramp_DownCorner_Asphalt_8x4_C": "Down Corner Ramp 4m (Asphalt)",
   "Build_Ramp_DownCorner_Concrete_8x1_C": "Down Corner Ramp 1m (Concrete)",
   "Build_Ramp_DownCorner_Concrete_8x2_C": "Down Corner Ramp 2m (Concrete)",
   "Build_Ramp_DownCorner_Concrete_8x4_C": "Down Corner Ramp 4m (Concrete)",
   "Build_Ramp_DownCorner_Metal_8x1_C": "Down Corner Ramp 1m (Metal)",
   "Build_Ramp_DownCorner_Metal_8x2_C": "Down Corner Ramp 2m (Metal)",
   "Build_Ramp_DownCorner_Metal_8x4_C": "Down Corner Ramp 4m (Metal)",
   "Build_Ramp_DownCorner_Polished_8x1_C": "Down Corner Ramp 1m (Polished)",
   "Build_Ramp_DownCorner_Polished_8x2_C": "Down Corner Ramp 2m (Polished)",
   "Build_Ramp_DownCorner_Polished_8x4_C": "Down Corner Ramp 4m (Polished)",
   "Build_Ramp_Frame_01_C": "Frame Ramp",
   "Build_Ramp_Frame_Inverted_01_C": "Inverted Frame Ramp",
   "Build_Ramp_Metal_8x1_C": "Ramp 1m (Metal)",
   "Build_Ramp_Metal_8x2_C": "Ramp 2m (Metal)",
   "Build_Ramp_Metal_8x4_C": "Ramp 4m (Metal)",
   "Build_Ramp_Polished_8x1_C": "Ramp 1m (Polished)",
   "Build_Ramp_Polished_8x2_C": "Ramp 2m (Polished)",
   "Build_Ramp_Polished_8x4_C": "Ramp 4m (Polished)",
   "Build_Ramp_UpCorner_Asphalt_8x1_C": "Up Corner Ramp 1m (Asphalt)",
   "Build_Ramp_UpCorner_Asphalt_8x2_C": "Up Corner Ramp 2m (Asphalt)",
   "Build_Ramp_UpCorner_Asphalt_8x4_C": "Up Corner Ramp 4m (Asphalt)",
   "Build_Ramp_UpCorner_Concrete_8x1_C": "Up Corner Ramp 1m (Concrete)",
   "Build_Ramp_UpCorner_Concrete_8x2_C": "Up Corner Ramp 2m (Concrete)",
   "Build_Ramp_UpCorner_Concrete_8x4_C": "Up Corner Ramp 4m (Concrete)",
   "Build_Ramp_UpCorner_Metal_8x1_C": "Up Corner Ramp 1m (Metal)",
   "Build_Ramp_UpCorner_Metal_8x2_C": "Up Corner Ramp 2m (Metal)",
   "Build_Ramp_UpCorner_Metal_8x4_C": "Up Corner Ramp 4m (Metal)",
   "Build_Ramp_UpCorner_Polished_8x1_C": "Up Corner Ramp 1m (Polished)",
   "Build_Ramp_UpCorner_Polished_8x2_C": "Up Corner Ramp 2m (Polished)",
   "Build_Ramp_UpCorner_Polished_8x4_C": "Up Corner Ramp 4m (Polished)",
   "Build_ResourceSinkShop_C": "AWESOME Shop",
   "Build_ResourceSink_C": "AWESOME Sink",
   "Build_Roof_A_01_C": "Roof Flat (Asphalt)",
   "Build_Roof_A_02_C": "Roof 1m (Asphalt)",
   "Build_Roof_A_03_C": "Roof 2m (Asphalt)",
   "Build_Roof_A_04_C": "Roof 4m (Asphalt)",
   "Build_Roof_Metal_InCorner_01_C": "Inner Corner Roof 1m (Metal)",
   "Build_Roof_Metal_InCorner_02_C": "Inner Corner Roof 2m (Metal)",
   "Build_Roof_Metal_InCorner_03_C": "Inner Corner Roof 4m (Metal)",
   "Build_Roof_Metal_OutCorner_01_C": "Outer Corner Roof 1m (Metal)",
   "Build_Roof_Metal_OutCorner_02_C": "Outer Corner Roof 2m (Metal)",
   "Build_Roof_Metal_OutCorner_03_C": "Outer Corner Roof 4m (Metal)",
   "Build_Roof_Orange_01_C": "Roof Flat (Orange)",
   "Build_Roof_Orange_02_C": "Roof 1m (Orange)",
   "Build_Roof_Orange_03_C": "Roof 2m (Orange)",
   "Build_Roof_Orange_04_C": "Roof 4m (Orange)",
   "Build_Roof_Orange_InCorner_01_C": "Inner Corner Roof 1m (Orange)",
   "Build_Roof_Orange_InCorner_02_C": "Inner Corner Roof 2m (Orange)",
   "Build_Roof_Orange_InCorner_03_C": "Inner Corner Roof 4m (Orange)",
   "Build_Roof_Orange_OutCorner_01_C": "Outer Corner Roof 1m (Orange)",
   "Build_Roof_Orange_OutCorner_02_C": "Outer Corner Roof 2m (Orange)",
   "Build_Roof_Orange_OutCorner_03_C": "Outer Corner Roof 4m (Orange)",
   "Build_Roof_Tar_01_C": "Roof Flat (Tar)",
   "Build_Roof_Tar_02_C": "Roof 1m (Tar)",
   "Build_Roof_Tar_03_C": "Roof 2m (Tar)",
   "Build_Roof_Tar_04_C": "Roof 4m (Tar)",
   "Build_Roof_Tar_InCorner_01_C": "Inner Corner Roof 1m (Tar)",
   "Build_Roof_Tar_InCorner_02_C": "Inner Corner Roof 2m (Tar)",
   "Build_Roof_Tar_InCorner_03_C": "Inner Corner Roof 4m (Tar)",
   "Build_Roof_Tar_OutCorner_01_C": "Outer Corner Roof 1m (Tar)",
   "Build_Roof_Tar_OutCorner_02_C": "Outer Corner Roof 2m (Tar)",
   "Build_Roof_Tar_OutCorner_03_C": "Outer Corner Roof 4m (Tar)",
   "Build_Roof_Window_01_C": "Roof Flat (Window)",
   "Build_Roof_Window_02_C": "Roof 1m (Window)",
   "Build_Roof_Window_03_C": "Roof 2m (Window)",
   "Build_Roof_Window_04_C": "Roof 4m (Window)",
   "Build_Roof_Window_InCorner_01_C": "Inner Corner Roof 1m (Window)",
   "Build_Roof_Window_InCorner_02_C": "Inner Corner Roof 2m (Window)",
   "Build_Roof_Window_InCorner_03_C": "Inner Corner Roof 4m (Window)",
   "Build_Roof_Window_OutCorner_01_C": "Outer Corner Roof 1m (Window)",
   "Build_Roof_Window_OutCorner_02_C": "Outer Corner Roof 2m (Window)",
   "Build_Roof_Window_OutCorner_03_C": "Outer Corner Roof 4m (Window)",
   "Build_SignPole_C": "Sign Pole, Small", # Not a separate item
   "Build_SignPole_Medium_C": "Sign Pole, Medium", # Not a separate item
   "Build_SM_RailingRamp_8x1_01_C": "SM_RailingRamp_8x1_01",
   "Build_SM_RailingRamp_8x2_01_C": "SM_RailingRamp_8x2_01",
   "Build_SM_RailingRamp_8x4_01_C": "SM_RailingRamp_8x4_01",
   "Build_SmelterMk1_C": "Smelter",
   "Build_SMM_C": "Somersloop Finder", # Mod: Somersloop Finder
   "Build_SnowDispenser_C": "FICSMAS Snow Dispenser",
   "Build_Snowman_C": "Snowman",
   "Build_SpaceElevator_C": "Space Elevator",
   "Build_Stairs_Left_01_C": "Stairs Left",
   "Build_Stairs_Right_01_C": "Stairs Right",
   "Build_StandaloneWidgetSign_Huge_C": "Large Billboard",
   "Build_StandaloneWidgetSign_Large_C": "Small Billboard",
   "Build_StandaloneWidgetSign_Medium_C": "Display Sign",
   "Build_StandaloneWidgetSign_Portrait_C": "Portrait Sign",
   "Build_StandaloneWidgetSign_SmallVeryWide_C": "Label Sign 4m",
   "Build_StandaloneWidgetSign_SmallWide_C": "Label Sign 3m",
   "Build_StandaloneWidgetSign_Small_C": "Label Sign 2m",
   "Build_StandaloneWidgetSign_Square_C": "Square Sign 2m",
   "Build_StandaloneWidgetSign_Square_Small_C": "Square Sign 1m",
   "Build_StandaloneWidgetSign_Square_Tiny_C": "Square Sign 0.5m",
   "Build_SteelWall_8x1_C": "Basic Wall 1m",
   "Build_SteelWall_8x4_C": "Tilted Wall 4m",
   "Build_SteelWall_8x4_Gate_01_C": "Gate Hole Wall",
   "Build_SteelWall_8x4_Window_01_C": "Single Window",
   "Build_SteelWall_8x4_Window_02_C": "Reinforced Window",
   "Build_SteelWall_8x4_Window_03_C": "Frame Window",
   "Build_SteelWall_8x4_Window_04_C": "Panel Window",
   "Build_SteelWall_FlipTris_8x1_C": "Inv. Ramp Wall 1m",
   "Build_SteelWall_FlipTris_8x2_C": "Inv. Ramp Wall 2m",
   "Build_SteelWall_FlipTris_8x4_C": "Inv. Ramp Wall 4m",
   "Build_SteelWall_FlipTris_8x8_C": "Inv. Ramp Wall 8m",
   "Build_SteelWall_Tris_8x1_C": "Ramp Wall 1m",
   "Build_SteelWall_Tris_8x2_C": "Ramp Wall 2m",
   "Build_SteelWall_Tris_8x4_C": "Ramp Wall 4m",
   "Build_SteelWall_Tris_8x8_C": "Ramp Wall 8m",
   "Build_StorageBlueprint_C": "Blueprint Storage Box",
   "Build_StorageContainerMk1_C": "Storage Container",
   "Build_StorageContainerMk2_C": "Industrial Storage Container",
   "Build_StorageHazard_C": "Hazard Storage Box",
   "Build_StorageIntegrated_C": "Personal Storage Box",
   "Build_StorageMedkit_C": "Medical Storage Box",
   "Build_StoragePlayer_C": "Personal Storage Box",
   "Build_StreetLight_C": "Street Light",
   "Build_TetrominoGame_Computer_C": "Productive Packer Deluxe",
   "Build_TradingPost_C": "The HUB",
   "Build_TrainDockingStationLiquid_C": "Fluid Freight Platform",
   "Build_TrainDockingStation_C": "Freight Platform",
   "Build_TrainPlatformEmpty_02_C": "Empty Platform With Catwalk",
   "Build_TrainPlatformEmpty_C": "Empty Platform",
   "Build_TrainStation_C": "Train Station",
   "Build_TreeGiftProducer_C": "FICSMAS Gift Tree",
   "Build_TruckStation_C": "Truck Station",
   "Build_TubeCannon_C": "Hypertube Entrance Mk.3", # Mod: BetterHypertybes
   "Build_Valve_C": "Valve",
   "Build_WalkwayCross_C": "Walkway Crossing",
   "Build_WalkwayRamp_C": "Walkway Ramp",
   "Build_WalkwayStraight_C": "Walkway Straight",
   "Build_WalkwayT_C": "Walkway T-Crossing",
   "Build_WalkwayTrun_C": "Walkway Turn",
   "Build_WallSet_Steel_Angular_8x4_C": "Tilted Wall 4m",
   "Build_WallSet_Steel_Angular_8x8_C": "Tilted Wall 8m",
   "Build_Wall_8x4_01_C": "Basic Wall 4m",
   "Build_Wall_8x4_02_C": "Basic Wall 4m",
   "Build_Wall_Concrete_8x1_C": "Basic Wall 1m",
   "Build_Wall_Concrete_8x4_C": "Basic Wall 4m",
   "Build_Wall_Concrete_8x4_ConveyorHole_01_C": "Conveyor Wall x1",
   "Build_Wall_Concrete_8x4_ConveyorHole_02_C": "Conveyor Wall x2",
   "Build_Wall_Concrete_8x4_ConveyorHole_03_C": "Conveyor Wall x3",
   "Build_Wall_Concrete_8x4_Corner_01_C": "Tilted Corner Wall 4m",
   "Build_Wall_Concrete_8x4_Corner_2_C": "Tilted Concave Wall 4m",
   "Build_Wall_Concrete_8x4_Window_01_C": "Single Window",
   "Build_Wall_Concrete_8x4_Window_02_C": "Frame Window",
   "Build_Wall_Concrete_8x4_Window_03_C": "Panel Window",
   "Build_Wall_Concrete_8x4_Window_04_C": "Reinforced Window",
   "Build_Wall_Concrete_8x8_Corner_01_C": "Tilted Corner Wall 8m",
   "Build_Wall_Concrete_8x8_Corner_2_C": "Tilted Concave Wall 8m",
   "Build_Wall_Concrete_Angular_8x4_C": "Tilted Wall 4m",
   "Build_Wall_Concrete_Angular_8x8_C": "Tilted Wall 8m",
   "Build_Wall_Concrete_CDoor_8x4_C": "Center Door Wall",
   "Build_Wall_Concrete_FlipTris_8x1_C": "Inv. Ramp Wall 1m",
   "Build_Wall_Concrete_FlipTris_8x2_C": "Inv. Ramp Wall 2m",
   "Build_Wall_Concrete_FlipTris_8x4_C": "Inv. Ramp Wall 4m",
   "Build_Wall_Concrete_FlipTris_8x8_C": "Inv. Ramp Wall 8m",
   "Build_Wall_Concrete_Gate_8x4_C": "Gate Hole Wall",
   "Build_Wall_Concrete_SDoor_8x4_C": "Side Door Wall",
   "Build_Wall_Concrete_Tris_8x1_C": "Ramp Wall 1m (Concrete)",
   "Build_Wall_Concrete_Tris_8x2_C": "Ramp Wall 2m (Concrete)",
   "Build_Wall_Concrete_Tris_8x4_C": "Ramp Wall 4m (Concrete)",
   "Build_Wall_Concrete_Tris_8x8_C": "Ramp Wall 8m (Concrete)",
   "Build_Wall_Conveyor_8x4_01_C": "Conveyor Wall x3",
   "Build_Wall_Conveyor_8x4_01_Steel_C": "Conveyor Wall x3",
   "Build_Wall_Conveyor_8x4_02_C": "Conveyor Wall x2",
   "Build_Wall_Conveyor_8x4_02_Steel_C": "Conveyor Wall x2",
   "Build_Wall_Conveyor_8x4_03_C": "Conveyor Wall x1",
   "Build_Wall_Conveyor_8x4_03_Steel_C": "Conveyor Wall x1",
   "Build_Wall_Conveyor_8x4_04_C": "Wall Conveyor Perpendicular",
   "Build_Wall_Conveyor_8x4_04_Steel_C": "Wall Conveyor Perpendicular",
   "Build_Wall_Door_8x4_01_C": "Center Door Wall",
   "Build_Wall_Door_8x4_01_Steel_C": "Center Door Wall",
   "Build_Wall_Door_8x4_03_C": "Side Door Wall",
   "Build_Wall_Door_8x4_03_Steel_C": "Side Door Wall",
   "Build_Wall_Frame_01_C": "Frame Wall",
   "Build_Wall_Gate_8x4_01_C": "Gate Hole Wall",
   "Build_Wall_Orange_8x1_C": "Basic Wall 1m",
   "Build_Wall_Orange_8x4_Corner_01_C": "Tilted Corner Wall 4m",
   "Build_Wall_Orange_8x4_Corner_02_C": "Tilted Concave Wall 4m",
   "Build_Wall_Orange_8x8_Corner_01_C": "Tilted Corner Wall 8m",
   "Build_Wall_Orange_8x8_Corner_02_C": "Tilted Concave Wall 8m",
   "Build_Wall_Orange_Angular_8x4_C": "Tilted Wall 4m",
   "Build_Wall_Orange_Angular_8x8_C": "Tilted Wall 8m",
   "Build_Wall_Orange_FlipTris_8x1_C": "Inv. Ramp Wall 1m",
   "Build_Wall_Orange_FlipTris_8x2_C": "Inv. Ramp Wall 2m",
   "Build_Wall_Orange_FlipTris_8x4_C": "Inv. Ramp Wall 4m",
   "Build_Wall_Orange_FlipTris_8x8_C": "Inv. Ramp Wall 8m",
   "Build_Wall_Orange_Tris_8x1_C": "Ramp Wall 1m (Orange)",
   "Build_Wall_Orange_Tris_8x2_C": "Ramp Wall 2m (Orange)",
   "Build_Wall_Orange_Tris_8x4_C": "Ramp Wall 4m (Orange)",
   "Build_Wall_Orange_Tris_8x8_C": "Ramp Wall 8m (Orange)",
   "Build_Wall_Steel_8x4_Corner_01_C": "Tilted Corner Wall 4m",
   "Build_Wall_Steel_8x4_Corner_2_C": "Tilted Concave Wall 4m",
   "Build_Wall_Steel_8x8_Corner_01_C": "Tilted Corner Wall 8m",
   "Build_Wall_Steel_8x8_Corner_2_C": "Tilted Concave Wall 8m",
   "Build_Wall_Window_8x4_01_C": "Single Window",
   "Build_Wall_Window_8x4_02_C": "Frame Window",
   "Build_Wall_Window_8x4_03_C": "Panel Window",
   "Build_Wall_Window_8x4_04_C": "Reinforced Window",
   "Build_Wall_Window_Thin_8x4_01_C": "Full Frame Window",
   "Build_Wall_Window_Thin_8x4_02_C": "Hex Frame Window",
   "Build_WaterPump_C": "Water Extractor",
   "Build_WorkBenchIntegrated_C": "Craft Bench",
   "Build_WorkBench_C": "Craft Bench",
   "Build_Workshop_C": "Equipment Workshop",
   "Build_WreathDecor_C": "FICSMAS Wreath",
   "Build_XmassLightsLine_C": "FICSMAS Power Light",
   "Build_XmassTree_C": "Giant FICSMAS Tree",

   # Items
   "Desc_AlienDNACapsule_C": "Alien DNA Capsule",
   "Desc_AlienProtein_C": "Alien Protein",
   "Desc_AluminaSolution_C": "Alumina Solution",
   "Desc_AluminumCasing_C": "Aluminum Casing",
   "Desc_AluminumIngot_C": "Aluminum Ingot",
   "Desc_AluminumPlateReinforced_C": "Heat Sink",
   "Desc_AluminumPlate_C": "Alclad Aluminum Sheet",
   "Desc_AluminumScrap_C": "Aluminum Scrap",
   "Desc_Battery_C": "Battery",
   "Desc_BerryBush_C": "Berry Bush Plant",
   "Desc_Berry_C": "Paleberry",
   "Desc_Biofuel_C": "Solid Biofuel",
   "Desc_BoomBox_C": "Boombox",
   "Desc_Cable_C": "Cable",
   "Desc_Camera_C": "AWESOME Camera",
   "Desc_CandyCane_C": "Candy Cane",
   "Desc_CartridgeChaos_C": "Turbo Rifle Ammo",
   "Desc_CartridgePlasma_C": "Rifle Plasmidge",
   "Desc_CartridgeSmartProjectile_C": "Homing Rifle Ammo",
   "Desc_CartridgeSmart_C": "Rifle Smartridge",
   "Desc_CartridgeStandard_C": "Rifle Ammo",
   "Desc_Cement_C": "Concrete",
   "Desc_Chainsaw_C": "Chainsaw",
   "Desc_CharacterClap_Statue_C": "Pretty Good Pioneering Statue",
   "Desc_CharacterRunStatue_C": "Adequate Pioneering Statue",
   "Desc_CharacterSpin_Statue_C": "Satisfactory Pioneering Statue",
   "Desc_CircuitBoardHighSpeed_C": "AI Limiter",
   "Desc_CircuitBoard_C": "Circuit Board",
   "Desc_Coal_C": "Coal",
   "Desc_ColorCartridge_C": "Color Cartridge",
   "Desc_CompactedCoal_C": "Compacted Coal",
   "Desc_ComputerSuper_C": "Supercomputer",
   "Desc_Computer_C": "Computer",
   "Desc_CoolingSystem_C": "Cooling System",
   "Desc_CopperDust_C": "Copper Powder",
   "Desc_CopperIngot_C": "Copper Ingot",
   "Desc_CopperSheet_C": "Copper Sheet",
   "Desc_CrystalOscillator_C": "Crystal Oscillator",
   "Desc_CrystalShard_C": "Power Shard",
   "Desc_Crystal_C": "Blue Power Slug",
   "Desc_Crystal_mk2_C": "Yellow Power Slug",
   "Desc_Crystal_mk3_C": "Purple Power Slug",
   "Desc_DarkMatter_C": "Dark Matter Crystal",
   "Desc_Diamond_C": "Diamonds",
   "Desc_DoggoStatue_C": "Lizard Doggo Statue",
   "Desc_DowsingStick_C": "Dowsing stick",
   "Desc_ElectromagneticControlRod_C": "Electromagnetic Control Rod",
   "Desc_Fabric_C": "Fabric",
   "Desc_FicsiteIngot_C": "Ficsite Ingot",
   "Desc_FicsiteMesh_C": "Ficsite Trigon",
   "Desc_Ficsonium_C": "Ficsonium",
   "Desc_FicsoniumFuelRod_C": "Ficsonium Fuel Rod",
   "Desc_Filter_C": "Gas Filter",
   "Desc_Fireworks_Projectile_01_C": "Sweet Fireworks",
   "Desc_Fireworks_Projectile_02_C": "Fancy Fireworks",
   "Desc_Fireworks_Projectile_03_C": "Sparkly Fireworks",
   "Desc_FlowerPetals_C": "Flower Petals",
   "Desc_FluidCanister_C": "Empty Canister",
   "Desc_Fuel_C": "Packaged Fuel",
   "Desc_GasTank_C": "Empty Fluid Tank",
   "Desc_GenericBiomass_C": "Biomass",
   "Desc_Geyser_C": "Geyser",
   "Desc_Gift_C": "FICSMAS Gift",
   "Desc_GoldIngot_C": "Caterium Ingot",
   "Desc_GoldenNut_Statue_C": "Golden Nut Statue",
   "Desc_GolfCart_C": "Factory Cart(TM)",
   "Desc_GolfCartGold_C": "Golden Factory Cart(TM)",
   "Desc_GunpowderMK2_C": "Smokeless Powder",
   "Desc_Gunpowder_C": "Black Powder",
   "Desc_HUBParts_C": "HUB Parts",
   "Desc_HardDrive_C": "Hard Drive",
   "Desc_HatcherBasic_C": "Tropical Crab Hatcher",
   "Desc_HatcherParts_C": "Hatcher Remains",
   "Desc_HazmatFilter_C": "Iodine Infused Filter",
   "Desc_HeavyOilResidue_C": "Heavy Oil Residue",
   "Desc_HighSpeedConnector_C": "High-Speed Connector",
   "Desc_HighSpeedWire_C": "Quickwire",
   "Desc_HogParts_C": "Hog Remains",
   "Desc_Hog_Statue_C": "Silver Hog Statue",
   "Desc_HostileCreature_C": "Enemies",
   "Desc_HydrogenGas_C": "Hydrogen Gas",
   "Desc_IronIngot_C": "Iron Ingot",
   "Desc_IronPlateReinforced_C": "Reinforced Iron Plate",
   "Desc_IronPlate_C": "Iron Plate",
   "Desc_IronRod_C": "Iron Rod",
   "Desc_IronScrew_C": "Screw",
   "Desc_Leaves_C": "Leaves",
   "Desc_LiquidBiofuel_C": "Liquid Biofuel",
   "Desc_LiquidFuel_C": "Fuel",
   "Desc_LiquidOil_C": "Crude Oil",
   "Desc_LiquidTurboFuel_C": "Turbofuel",
   "Desc_Medkit_C": "Medicinal Inhaler",
   "Desc_ModularFrameFused_C": "Fused Modular Frame",
   "Desc_ModularFrameHeavy_C": "Heavy Modular Frame",
   "Desc_ModularFrameLightweight_C": "Radio Control Unit",
   "Desc_ModularFrame_C": "Modular Frame",
   "Desc_MotorLightweight_C": "Turbo Motor",
   "Desc_Motor_C": "Motor",
   "Desc_Mycelia_C": "Mycelia",
   "Desc_NaturalGas_C": "Natural Gas",
   "Desc_NitricAcid_C": "Nitric Acid",
   "Desc_NitrogenGas_C": "Nitrogen Gas",
   "Desc_NobeliskCluster_C": "Cluster Nobelisk",
   "Desc_NobeliskExplosive_C": "Nobelisk",
   "Desc_NobeliskGas_C": "Gas Nobelisk",
   "Desc_NobeliskNuke_C": "Nuke Nobelisk",
   "Desc_NobeliskShockwave_C": "Pulse Nobelisk",
   "Desc_NonFissibleUranium_C": "Non-fissile Uranium",
   "Desc_NuclearFuelRod_C": "Uranium Fuel Rod",
   "Desc_NuclearWaste_C": "Uranium Waste",
   "Desc_NutBush_C": "Nut Bush Plant",
   "Desc_Nut_C": "Beryl Nut",
   "Desc_OreBauxite_C": "Bauxite",
   "Desc_OreCopper_C": "Copper Ore",
   "Desc_OreGold_C": "Caterium Ore",
   "Desc_OreIron_C": "Iron Ore",
   "Desc_OreUranium_C": "Uranium",
   "Desc_PackagedAlumina_C": "Packaged Alumina Solution",
   "Desc_PackagedBiofuel_C": "Packaged Liquid Biofuel",
   "Desc_PackagedIonizedFuel_C": "Packaged Ionized Fuel",
   "Desc_PackagedNitricAcid_C": "Packaged Nitric Acid",
   "Desc_PackagedNitrogenGas_C": "Packaged Nitrogen Gas",
   "Desc_PackagedOilResidue_C": "Packaged Heavy Oil Residue",
   "Desc_PackagedOil_C": "Packaged Oil",
   "Desc_PackagedRocketFuel_C": "Packaged Rocket Fuel",
   "Desc_PackagedSulfuricAcid_C": "Packaged Sulfuric Acid",
   "Desc_PackagedWater_C": "Packaged Water",
   "Desc_Parachute_C": "Parachute",
   "Desc_PetroleumCoke_C": "Petroleum Coke",
   "Desc_Pigment_C": "Pigment",
   "Desc_Plastic_C": "Plastic",
   "Desc_PlutoniumCell_C": "Encased Plutonium Cell",
   "Desc_PlutoniumFuelRod_C": "Plutonium Fuel Rod",
   "Desc_PlutoniumPellet_C": "Plutonium Pellet",
   "Desc_PlutoniumWaste_C": "Plutonium Waste",
   "Desc_PolymerResin_C": "Polymer Resin",
   "Desc_PressureConversionCube_C": "Pressure Conversion Cube",
   "Desc_PropaneGas_C": "Propane Gas",
   "Desc_QuantumCrystal_C": "Quantum Crystal",
   "Desc_QuantumOscillator_C": "Superposition Oscillator",
   "Desc_QuartzCrystal_C": "Quartz Crystal",
   "Desc_RawQuartz_C": "Raw Quartz",
   "Desc_RebarGunProjectile_C": "Rebar Gun",
   "Desc_RebarGun_C": "Rebar Gun (OLD)",
   "Desc_Rebar_Aluminum_C": "Aluminum Rebar",
   "Desc_Rebar_ChemicalShot_C": "Rebar Syringe",
   "Desc_Rebar_Explosive_C": "Explosive Rebar",
   "Desc_Rebar_Hookshot_C": "Rebar Hookshot",
   "Desc_Rebar_Rocket_C": "Rocket Rebar",
   "Desc_Rebar_Spreadshot_C": "Shatter Rebar",
   "Desc_Rebar_Steel_C": "Steel Rebar",
   "Desc_Rebar_Stunshot_C": "Stun Rebar",
   "Desc_ResourceSinkCoupon_C": "FICSIT Coupon",
   "Desc_RocketFuel_C": "Rocket Fuel",
   "Desc_Rotor_C": "Rotor",
   "Desc_Rubber_C": "Rubber",
   "Desc_SAMFluctuator_C": "SAM Fluctuator",
   "Desc_SAMIngot_C": "SAM Ingot",
   "Desc_SAM_C": "SAM Ore",
   "Desc_Shroom_C": "Bacon Agaric",
   "Desc_Silica_C": "Silica",
   "Desc_SingularityCell_C": "Singularity Cell",
   "Desc_Snow_C": "Actual Snow",
   "Desc_SnowballProjectile_C": "Snowball",
   "Desc_SpaceElevatorPart_1_C": "Smart Plating",
   "Desc_SpaceElevatorPart_2_C": "Versatile Framework",
   "Desc_SpaceElevatorPart_3_C": "Automated Wiring",
   "Desc_SpaceElevatorPart_4_C": "Modular Engine",
   "Desc_SpaceElevatorPart_5_C": "Adaptive Control Unit",
   "Desc_SpaceElevatorPart_6_C": "Magnetic Field Generator",
   "Desc_SpaceElevatorPart_7_C": "Assembly Director System",
   "Desc_SpaceElevatorPart_8_C": "Thermal Propulsion Rocket",
   "Desc_SpaceElevatorPart_9_C": "Nuclear Pasta",
   "Desc_SpaceElevatorPart_10_C": "Biochemical Sculptor",
   "Desc_SpaceElevatorPart_11_C": "Ballistic Warp Drive",
   "Desc_SpaceElevatorPart_12_C": "AI Expansion Server",
   "Desc_SpaceGiraffeStatue_C": "Confusing Creature Statue",
   "Desc_SpikedRebar_C": "Iron Rebar",
   "Desc_SpitterParts_C": "Plasma Spitter Remains",
   "Desc_SpitterWave_C": "Spitter Wave",
   "Desc_Stator_C": "Stator",
   "Desc_SteelIngot_C": "Steel Ingot",
   "Desc_SteelPipe_C": "Steel Pipe",
   "Desc_SteelPlateReinforced_C": "Encased Industrial Beam",
   "Desc_SteelPlate_C": "Steel Beam",
   "Desc_StingerParts_C": "Stinger Remains",
   "Desc_Stone_C": "Limestone",
   "Desc_Sulfur_C": "Sulfur",
   "Desc_SulfuricAcid_C": "Sulfuric Acid",
   "Desc_TemporalProcessor_C": "Neural-Quantum Processor",
   "Desc_TimeCrystal_C": "Time Crystal",
   "Desc_ToolBelt_C": "Tool Belt",
   "Desc_TurboFuel_C": "Packaged Turbofuel",
   "Desc_UraniumCell_C": "Encased Uranium Cell",
   "Desc_UraniumPellet_C": "Uranium Pellet",
   "Desc_VolcanicGas_C": "Volcanic Gas",
   "Desc_WAT1_C": "Somersloop",
   "Desc_WAT2_C": "Mercer Sphere",
   "Desc_Water_C": "Water",
   "Desc_Wildcard_C": "Any",
   "Desc_Wire_C": "Wire",
   "Desc_Wood_C": "Wood",
   "Desc_XmasBall1_C": "Red FICSMAS Ornament",
   "Desc_XmasBall2_C": "Blue FICSMAS Ornament",
   "Desc_XmasBall3_C": "Copper FICSMAS Ornament",
   "Desc_XmasBall4_C": "Iron FICSMAS Ornament",
   "Desc_XmasBallCluster_C": "FICSMAS Ornament Bundle",
   "Desc_XmasBow_C": "FICSMAS Bow",
   "Desc_XmasBranch_C": "FICSMAS Tree Branch",
   "Desc_XmasLights_C": "FICSMAS Lights",
   "Desc_XmasStar_C": "FICSMAS Wonder Star",
   "Desc_XmasWreath_C": "FICSMAS Decoration",
   "Desc_Zipline_C": "Zipline",

   # Milestones
   "Schematic_Tutorial1_C": "HUB Upgrade 1",
   "Schematic_Tutorial1_5_C": "HUB Upgrade 2",
   "Schematic_Tutorial2_C": "HUB Upgrade 3",
   "Schematic_Tutorial3_C": "HUB Upgrade 4",
   "Schematic_Tutorial4_C": "HUB Upgrade 5",
   "Schematic_Tutorial5_C": "HUB Upgrade 6",
   "Schematic_1-1_C": "Base Building",
   "Schematic_1-2_C": "Logistics",
   "Schematic_1-3_C": "Field Research",
   "Schematic_2-1_C": "Part Assembly",
   "Schematic_2-2_C": "Obstacle Clearing",
   "Schematic_2-3_C": "Jump Pads",
   "Schematic_2-5_C": "Resource Sink Bonus Program",
   "Schematic_3-2_C": "Logistics Mk.2",
   "Schematic_3-1_C": "Coal Power",
   "Schematic_3-3_C": "Vehicular Transport",
   "Schematic_3-4_C": "Basic Steel Production",
   "Schematic_4-2_C": "Enhanced Asset Security",
   "Schematic_4-1_C": "Advanced Steel Production",
   "Schematic_4-3_C": "Expanded Power Infrastructure",
   "Schematic_4-4_C": "Hypertubes",
   "Schematic_5-3_C": "Logistics Mk.3",
   "Schematic_4-5_C": "FICSIT Blueprints",
   "Schematic_5-1_C": "Oil Processing",
   "Schematic_5-1-1_C": "Oil Processing 2",
   "Schematic_5-2_C": "Industrial Manufacturing",
   "Schematic_5-4_C": "Fluid Packaging",
   "Schematic_5-4-1_C": "Alternative Fluid Transport 2",
   "Schematic_5-5_C": "Petroleum Power",
   "Schematic_6-1_C": "Logistics Mk.4",
   "Schematic_6-2_C": "Jetpack",
   "Schematic_6-3_C": "Monorail Train Technology",
   "Schematic_6-5_C": "Pipeline Engineering Mk.2",
   "Schematic_6-6_C": "FICSIT Blueprints Mk.2",
   "Schematic_7-1_C": "Bauxite Refinement",
   "Schematic_7-1-1_C": "Bauxite Refinement 2",
   "Schematic_7-2_C": "Logistics Mk.5",
   "Schematic_7-4_C": "Aeronautical Engineering",
   "Schematic_7-4-1_C": "Aeronautical Engineering 2",
   "Schematic_7-3_C": "Hazmat Suit",
   "Schematic_8-3_C": "Hover Pack",
   "Schematic_8-1_C": "Nuclear Power",
   "Schematic_8-2_C": "Advanced Aluminum Production",
   "Schematic_8-2-1_C": "Advanced Aluminum Production 2",
   "Schematic_8-4_C": "Leading-edge Production",
   "Schematic_8-5_C": "Particle Enrichment",
   "Schematic_8-5-1_C": "Particle Enrichment 2",
}
